add zip impl, add tests
frontend-park-mail-ru/homework_2022_1 pull request #1
Opened 2022-02-05 13:14 UTC by rflban

Набиев Фарис

2022-02-05 20:39 UTC, Sarafa2n requested changes
Привет! Поздравляю с переходом на курс фронтенда. Ты хорошо справился с дз, но есть пару вопросов, но я верю ты справишься

2022-02-05 20:39 UTC, Sarafa2n commented on tests/zip.js
> +	});
А что если кинуть не валидные данные к примеру массив или сторку?

2022-02-05 20:39 UTC, Sarafa2n commented on source/zip.js
> +            ),
Круто что знаешь такие методы, а давай сделаем через spread оператор

2022-02-05 20:39 UTC, Sarafa2n commented on source/zip.js
> +    return objs.reduceRight(
а почему именно reduceRight?

2022-02-05 20:39 UTC, Sarafa2n commented on source/zip.js
> +function zip(...objs) {
А можешь рассказать как это работает ?

2022-02-05 21:20 UTC, rflban commented on source/zip.js
> +'use strict';
чтобы отключить совместимость со старым стандартом js

2022-02-05 21:20 UTC, rflban commented on source/zip.js
> +function zip(...objs) {
что именно? ...objs это array-like представление списка переданных параметров

2022-02-05 21:20 UTC, rflban commented on source/zip.js
> +    return objs.reduceRight(
чтобы учитывалось только первое вхождения поля

2022-02-05 21:20 UTC, rflban commented on source/zip.js
> +            ),
{ ...curr, ...acc }

2022-02-05 21:20 UTC, rflban commented on source/zip.js
> +            ),
но тогда не будут копироваться не enumeratable поля и дескрипторы остальных полей

2022-02-05 21:20 UTC, rflban commented on tests/zip.js
> +	});
для строк/чисел создастся временный объект-обертка для скалярных типов, и скопируется именно он
в случае массива скопируется его объектное представление

2022-02-05 23:19 UTC, Sarafa2n commented on source/zip.js
> +function zip(...objs) {
давай использовать модные стрелочные функции

2022-02-06 22:12 UTC, rflban commented on source/zip.js
> +            ),
исправил

2022-02-06 22:12 UTC, rflban commented on source/zip.js
> +function zip(...objs) {
исправил

2022-02-06 22:13 UTC, rflban commented on tests/zip.js
> +	});
добавил тесты

2022-02-07 09:53 UTC, Sarafa2n requested changes

2022-02-07 09:53 UTC, Sarafa2n commented on source/zip.js
> +    * objs - objects to merge
Нет типа входных данных

2022-02-07 09:53 UTC, Sarafa2n commented on tests/zip.js
> +		assert.deepEqual(zip(1.1), {}, 'Результат копирования вещественного числа - пустой объект');
а что если кинуть NaN или Infinity

2022-02-07 11:52 UTC, rflban commented on source/zip.js
> +    * objs - objects to merge
исправил

2022-02-07 11:52 UTC, rflban commented on tests/zip.js
> +		assert.deepEqual(zip(1.1), {}, 'Результат копирования вещественного числа - пустой объект');
это значения типа number, поэтому поведение не будет отличаться от обычных чисел. добавил тесты

2022-02-08 08:20 UTC, Sarafa2n approved these changes

2022-02-10 21:32 UTC, Betchika99 requested changes
привет) добро пожаловать на курс.
- [ ] твое решение корректное, но давай добавим явную проверку на ошибки.
- [ ] тесты нужно переписать, т.к. они не проверяют корректную/некорректную работу функции (ты просто проверяешь, что функция не падает, но при этом ее назначение не выполняется, а выполняется какая-то внутренняя js-магия, это некорректно)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

p.s. вопрос "на засыпку". в JS есть [символы](https://learn.javascript.ru/symbol), которые также можно использовать в качестве ключей объектов. расскажи, как твоя функция поведет себя, если их использовать в передаваемых объектах

2022-02-10 21:32 UTC, Betchika99 commented on tests/zip.js
> +		assert.deepEqual(zip(), {});
разве пустой объект в этом случае валидный ответ?

2022-02-10 21:32 UTC, Betchika99 commented on source/zip.js
> +const zip = (...objs) => objs.reduce((acc, cur) => ({ ...cur, ...acc }), {});
лаконичное решение. Но смущает, что пользователь никогда не узнает, что он ввел что-то не то. Функция просто "проглотит" данные с неверным форматом и ничего не скажет. Мы учимся делать user-friendly интерфейсы, поэтому давай добавим явную валидацию и возврат человекочитаемых ошибок/исключений, которые можно будет обработать

2022-02-10 21:32 UTC, Betchika99 commented on tests/zip.js
> +	QUnit.test('Функция копирует временную объектную обёртку примитивных типов', function (assert) {
непонятное название, не говорит о работе теста

2022-02-10 21:32 UTC, Betchika99 commented on tests/zip.js
> +		assert.deepEqual(zip('1234', 'zzzz5'), {0: '1', 1: '2', 2: '3', 3: '4', 4: '5'}, 'Результат слияния строк - array-like объект символов');
почему такая работа функции считается корректной?

2022-02-11 15:21 UTC, rflban commented on tests/zip.js
> +		assert.deepEqual(zip(), {});
добавил проверку на то, что в функцию был передан хотя бы один аргумент

2022-02-11 15:22 UTC, rflban commented on tests/zip.js
> +	QUnit.test('Функция копирует временную объектную обёртку примитивных типов', function (assert) {
заменил на другой тест, который проверяет, что функция не работает с примитивными типами

2022-02-11 15:24 UTC, rflban commented on tests/zip.js
> +		assert.deepEqual(zip('1234', 'zzzz5'), {0: '1', 1: '2', 2: '3', 3: '4', 4: '5'}, 'Результат слияния строк - array-like объект символов');
ввиду запрета на передачу экземпляров примитивных типов, теперь это ошибка

2022-02-11 15:25 UTC, rflban commented
> p.s. вопрос "на засыпку". в JS есть [символы](https://learn.javascript.ru/symbol), которые также можно использовать в качестве ключей объектов. расскажи, как твоя функция поведет себя, если их использовать в передаваемых объектах

Spread-оператор разворачивает объект вместе с символами, поэтому они попадут в итоговый объект

2022-02-11 22:38 UTC, Betchika99 requested changes
уже лучше, но есть еще немного комментов. Ты сможешь! :)

2022-02-11 22:38 UTC, Betchika99 commented on source/zip.js
> +    if (
давай добавим между этими логическими блоками пустую строку, чтобы лучше читалось. ознакомься (если еще не видел) с принятым [код-стайлом в JS](https://learn.javascript.ru/coding-style) и проверь все свое решение на предмет стилистических ошибок :)

2022-02-11 22:38 UTC, Betchika99 commented on source/zip.js
> +        )
это очень сложная проверка с тз читаемости. Смотри, на неравенство null, undefined можно проверить просто `!obj`, а на соответствие типу объекта через `typeof = 'object'` (да, тут так можно, потому что ты ранее проверил на null)

2022-02-11 22:38 UTC, Betchika99 commented on source/zip.js
> +        !objs.every(
почему вместо !every не использовать some ?)))

2022-02-11 22:38 UTC, Betchika99 commented on tests/zip.js
> +		assert.throws(zip, new Error("Nothing to merge"));
а где вызов функции?)

2022-02-11 22:38 UTC, Betchika99 commented on tests/zip.js
> +        const error = new TypeError("Only pure objects can be merged");
кавычки одинарные в документе =(

2022-02-11 22:38 UTC, Betchika99 commented on tests/zip.js
> +        const error = new TypeError("Only pure objects can be merged");
таб потерялся

2022-02-11 23:06 UTC, rflban commented on source/zip.js
> +    if (
исправил

2022-02-11 23:11 UTC, rflban commented on source/zip.js
> +        !objs.every(
исправил

2022-02-11 23:11 UTC, rflban commented on tests/zip.js
> +		assert.throws(zip, new Error("Nothing to merge"));
внутри throws

2022-02-11 23:18 UTC, rflban commented on tests/zip.js
> +		assert.throws(zip, new Error("Nothing to merge"));
ойой, нет

2022-02-12 11:22 UTC, Betchika99 approved these changes

2022-02-12 11:22 UTC, closed without merging