Воронова Ольга, Вариант 2
frontend-park-mail-ru/homework_2022_1 pull request #10
Opened 2022-02-07 12:49 UTC by vorolga

2022-02-09 13:23 UTC, alexey-ershkov requested changes
Привет) Поздравляю с переходом на второй (и самый лучший) семестр технопарка) Я буду проверять твою домашку) Ты молодец, что использовала JSDoc. Я оставил тебе несколько комментов

Если будут вопросы - пиши мне в телеграмм @alexey_ershkov

2022-02-09 13:23 UTC, alexey-ershkov commented on source/euclid.js
> + * @example
Кажется ты перепутала порядок у тега @exapmle. Посмотри в [документацию](https://jsdoc.app/tags-example.html), либо обоснуй почему так.

2022-02-09 13:23 UTC, alexey-ershkov commented on source/euclid.js
> +}
Тоже нет переноса в конце

2022-02-09 13:23 UTC, alexey-ershkov commented on source/euclid.js
> +    numbers.slice(1).forEach(number => {
Давай для того, чтобы не делать `slice`, воспользуемся деструктурирующим присваиванием

2022-02-09 13:23 UTC, alexey-ershkov commented on source/euclid.js
> +        result += number;
В Javascript у массива есть множество методов, которые упрощают жизнь, давай воспользуемся одним из них -  методом для накопления результата в переменную - reduce.

2022-02-09 13:23 UTC, alexey-ershkov commented on tests/euclid.js
> +
Давай напишем еще пару блоков тестов - например на работу с простыми числами. Вторая идея с тебя)))

2022-02-09 13:23 UTC, alexey-ershkov commented on tests/euclid.js
> +		assert.throws(() => euclid(null), 'The arguments must be natural numbers');
А на все ли типы данных ты здесь проверяешь? Давай расширим тесты 

 Какие типы данных в Javascript ты знаешь?

2022-02-09 14:10 UTC, vorolga commented on .gitignore
> +.idea/
По стандарту POSIX
Если не ставить в конце строки символ переноса, то тогда эта строка по стандарту не является валидной

2022-02-09 14:22 UTC, vorolga commented on source/euclid.js
> +'use strict';
Это строгий режим
С помощью него можно быстрее находить ошибки, то есть в нестрогом режиме некоторые ошибки могут не отображаться, а в строгом наличие этих ошибок вызывает исключения

2022-02-09 14:24 UTC, vorolga commented on source/euclid.js
> + * @example
Да, перепутала

2022-02-09 14:31 UTC, vorolga commented on tests/euclid.js
> +		assert.throws(() => euclid(null), 'The arguments must be natural numbers');
Хорошо, добавлю 

number (числа в диапазоне ±(253-1)), 
bigint (целые числа произвольной длины), 
string (строка), 
boolean (true/false),
null (неизвестные значения),
undefined (неприсвоенные),
object (объекты, более сложные структуры данных),
symbol (уникальные идентификаторы)

2022-02-10 14:25 UTC, alexey-ershkov requested changes
Хорошая работа - но нашел еще несколько моментов) Отписал в комментах)

2022-02-10 14:25 UTC, alexey-ershkov commented on source/euclid.js
>          throw Error('There are no arguments');
В Javascript есть разные виды ошибок - давай для каждой ошибки, которую выбрасываем подберем соответствующий тип ошибки. Какие типы ошибок ты знаешь?

2022-02-10 14:25 UTC, alexey-ershkov commented on source/euclid.js
> +    if (!numbers.every(check => (Number.isInteger(check) || typeof check === 'bigint') && check > 0)) {
Давай вынесем проверку в отдельную функцию и будем передавать ее every. Почему не можем найти НОД больше 0? Подумай как это можно сделать

2022-02-10 14:25 UTC, alexey-ershkov commented on source/euclid.js
> +    [initialValue , ...nextNumbers] = numbers
Можно сразу написать `const [initialValue , ...nextNumbers] = numbers` и оно заработает. До этого можно не объявлять переменные

2022-02-10 14:25 UTC, alexey-ershkov commented on source/euclid.js
> +        console.log(currentValue, accumulator + currentValue);
Кажется этого быть не должно

2022-02-10 14:25 UTC, alexey-ershkov commented on tests/euclid.js
> +	QUnit.test('Функция должна правильно находить НОД простых чисел', function (assert) {
Дублирование тестов выше

2022-02-10 14:25 UTC, alexey-ershkov commented on tests/euclid.js
> +		assert.strictEqual(euclid(BigInt(900719925474099), 300239975158033n, 9007199254740990n), 300239975158033n, 'euclid(BigInt(900719925474099), 300239975158033n, 9007199254740990n) === 300239975158033n
Круто) Хорошие тесты - давай еще добавим тесты для отрицательных чисел

2022-02-10 14:25 UTC, alexey-ershkov commented on source/euclid.js
> +    return nextNumbers.reduce(function (accumulator, currentValue) {
Давай будем использовать модные стрелочные функции) В чем их отличие от обычных функций?

2022-02-10 15:00 UTC, vorolga commented on tests/euclid.js
> +		assert.strictEqual(euclid(BigInt(900719925474099), 300239975158033n, 9007199254740990n), 300239975158033n, 'euclid(BigInt(900719925474099), 300239975158033n, 9007199254740990n) === 300239975158033n
У меня есть один тест с отрицательным числом, он выдает исключение
По условию задачи на вход подаются натуральные, как я выше писала

2022-02-10 19:51 UTC, vorolga commented on source/euclid.js
> +    if (!numbers.every(check => (Number.isInteger(check) || typeof check === 'bigint') && check > 0)) {
Для отрицательных чисел необходимо просто использовать их модули, то есть перед нахождением НОД можно сделать
var numbers = numbers.map(number => number < 0 ? Math.abs(number) : number);
а дальше алгоритм такой же

2022-02-10 20:03 UTC, vorolga commented on source/euclid.js
> +    return nextNumbers.reduce(function (accumulator, currentValue) {
У стрелочной функци нет this. Если происходит обращение к  this, оно берётся из внешнего лексического окружения. Также не имеют arguments. 
В общем, стрелочные функции предназначены для небольшого кода, который не имеет своего «контекста», выполняясь в текущем.

2022-02-11 18:22 UTC, alexey-ershkov requested changes
Пара небольших правок и будет аппрув))

2022-02-11 18:22 UTC, alexey-ershkov commented on source/euclid.js
>      if (numbers.length === 0) {
`if (!numbers.length)`

2022-02-11 18:22 UTC, alexey-ershkov commented on source/euclid.js
> +const isValidType  = (element) => (Number.isInteger(element) || typeof element === 'bigint');
Последний вопрос - почему используешь тройное равно? Чем отличается от двойного и какое лучше использовать?

2022-02-11 18:28 UTC, alexey-ershkov commented on source/euclid.js
> +    if (!numbers.every(check => (Number.isInteger(check) || typeof check === 'bigint') && check > 0)) {
Супер) Все правильно, молодец)

2022-02-11 18:40 UTC, vorolga commented on source/euclid.js
> +const isValidType  = (element) => (Number.isInteger(element) || typeof element === 'bigint');
По факту в данном случае можно использовать ==, т. к. typeof возвращает стринг, и он всегда сравнивается со стрингом
== перед сравнением величин производит приведение типов
=== сравнивает величины без приведения типов, оно строгое
То есть, например, если мы сравним "1" == 1, то будет true, так как одинаковое значение
А если "1" === 1, будет false, так как разных типов

2022-02-11 18:44 UTC, vorolga commented on source/euclid.js
> +const isValidType  = (element) => (Number.isInteger(element) || typeof element === 'bigint');
== перед сравнением величин производит приведение типов
=== сравнивает величины без приведения типов, оно строгое
То есть, например, если мы сравним "1" == 1, то будет true, так как одинаковое значение
А если "1" === 1, будет false, так как разных типов

2022-02-12 19:25 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

ты хорошо справилась с задачей, молодец :) есть несколько комментов прошу обратить внимание.
и еще вопрос тебе "на засыпку": в рамках задания ты по-разному работала с числами (использовала isInteger, bigint и т.д.), а какие еще типы данных ты знаешь в js? классические и современные, в чем особенности. расскажи коротко и по сути, что знаешь)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-12 19:25 UTC, Betchika99 commented on source/euclid.js
> +    if (!numbers.every(isValidType)) {
почему бы вместо !every не использовать some?) здесь и далее

2022-02-12 19:25 UTC, Betchika99 commented on source/euclid.js
> +    const [initialValue , ...nextNumbers] = numbers
здесь лишний пробел и не хватает точки с запятой. Проверь пожалуйста всё свое решение на предмет корректного [код-стайла](https://learn.javascript.ru/coding-style)

2022-02-12 19:25 UTC, Betchika99 commented on source/euclid.js
> +            accumulator > currentValue ? accumulator %= currentValue : currentValue %= accumulator;
на этой строке ты меняешь `currentValue`. `currentValue` - это элемент массива `nextNumbers`, по которому ты проходишься циклом. то есть ты меняешь элементы массива в процессе прохода по массиву. это не очень хорошее решение. код должен работать максимально чисто и прозрачно

2022-02-13 19:08 UTC, vorolga commented on source/euclid.js
> +    if (!numbers.every(isValidType)) {
Метод every возвращает true, если вызов callback вернёт true для каждого элемента numbers
Метод some возвращает true, если вызов callback вернёт true для какого-нибудь элемента numbers

Мне необходимо, чтобы все элементы массива удовлетворяли условию, а не хотя бы один, как это делает метод some

2022-02-13 19:12 UTC, vorolga commented
Готово

2022-02-13 19:13 UTC, vorolga commented on source/euclid.js
> +    if (!numbers.every(isValidType)) {
А, я поняла, можно сделать some если хотя бы 1 не удовлетворяет условию

2022-02-13 19:19 UTC, vorolga commented
Готово

2022-02-13 20:13 UTC, closed without merging