Бахланов Даниил Вариант 1
frontend-park-mail-ru/homework_2022_1 pull request #11
Opened 2022-02-07 15:09 UTC by Similization

2022-02-09 17:10 UTC, alexey-ershkov commented on README.md
> -
Хорошая мысль причесать README, но все же условие задания не стоит удалять

2022-02-09 17:12 UTC, alexey-ershkov commented on source/zip.js
> +const zip = (...args) => {
args - довольно общее название, назови конкретнее входные аргументы. 

Обычно принято документировать код, добавь описание функции с помощью JSDoc

2022-02-09 17:17 UTC, alexey-ershkov commented on source/zip.js
> +    for (let i = 0; i < args.length; ++i) {
В Javascript-е довольно много методов у массива позволяющих сделать перебор. В данном случае у тебя есть переменная, в которую "набираются" данные, поэтому здесь хорошо подойдет `reduce`. Давай перепишем на него

2022-02-09 17:22 UTC, alexey-ershkov commented on source/zip.js
> +        for (let key in args[i]) {
Аналогично здесь подумай - можно ли здесь использовать особенности массивов? Может создать массив из ключей объекта и и проходится по нему один из методов массива 

Плюс, а что будет если будут не объекты в качестве аргументов? Давай добавим проверку на это

2022-02-09 17:24 UTC, alexey-ershkov commented on tests/zip.js
> +
Давай добавим набор тестов для невалидных данных

2022-02-10 16:48 UTC, Similization commented on source/zip.js
> +        for (let key in args[i]) {
Если на вход подать строку, произойдет преобразование "как в плюсах"
Например:
console.log(zip("abcdef"));
Выведет:
{
0: "a",
1: "b",
2: "c",
3: "d",
4: "e",
5: "f",
}
Если на вход подать число, например 123
console.log(zip("abcdef"));
Выведет:
{
}

2022-02-10 17:33 UTC, Similization commented on source/zip.js
> +const zip = (...args) => {
Добавил

2022-02-10 17:41 UTC, Similization commented on README.md
> -
Вернул условие

2022-02-11 18:19 UTC, alexey-ershkov requested changes
Отписал еще немного комментов

2022-02-11 18:19 UTC, alexey-ershkov commented on source/zip.js
> +const zip = (...objects) => objects.reduce((prevObj, nextObj) => ({...nextObj, ...prevObj}), {});
Красивое решение - лайк)

2022-02-11 18:19 UTC, alexey-ershkov commented on tests/zip.js
> +	QUnit.test('Непредвиденные входные данные', function (assert) {
Давай разделим пустыми строкам тесты, чтобы добавить "воздуха"

2022-02-11 18:19 UTC, alexey-ershkov commented on tests/zip.js
> +		assert.deepEqual(zip({a: obj1}, {a: obj2}), {a: obj1});
Давай сложные объекты для тестов формировать не в самом тесте, а внесем в переменные, это сделает тесты читаемее

соотвественно поправить нужно везде в тестах

2022-02-11 18:19 UTC, alexey-ershkov commented on source/zip.js
> +*/
Опять же пустая строка между описанием функции и решением тоже добавит читаемости

2022-02-12 10:02 UTC, Similization commented on tests/zip.js
> +		assert.deepEqual(zip({a: obj1}, {a: obj2}), {a: obj1});
Изменил

2022-02-12 10:02 UTC, Similization commented on tests/zip.js
> +	QUnit.test('Непредвиденные входные данные', function (assert) {
Готово

2022-02-12 10:04 UTC, Similization commented on source/zip.js
> +const zip = (...objects) => objects.reduce((prevObj, nextObj) => ({...nextObj, ...prevObj}), {});
Спасибо, но такой вопрос, должна ли функция проглатывать такие данные, как "null" и "undefined" или же должна осуществляться проверка и проброс ошибок ?

2022-02-12 10:54 UTC, alexey-ershkov commented on source/zip.js
> +*/
Стандарта нет - кому как привычнее. Я топлю за то, что так читаемее, тип ты явно разделяешь на блоки свой код) Этот момент обсуждаем - если есть аргументы за то, чтобы так не делать - давай обсудим, это привествуется

2022-02-12 11:05 UTC, alexey-ershkov requested changes
Написал еще комментов

2022-02-12 11:05 UTC, alexey-ershkov commented on source/zip.js
> +const zip = (...objects) => objects.reduce((prevObj, nextObj) => ({...nextObj, ...prevObj}), {});
Мне кажется, что пустой объект в качестве результата выглядит довольно логично, ибо логично выкидывать ошибку в том случае, когда ты не можешь работать со входными данными.

Пример - ты ожидаешь на вход массив в качестве переменной и используешь метод `map` у него. А тебе на вход в качестве переменной передают `true`. У `Boolean` нет метода `map` поэтому выполнить логику функция и не может. Как раз в таком случае есть смысл выбрасывать ошибку

2022-02-12 11:05 UTC, alexey-ershkov commented on tests/zip.js
> +		assert.deepEqual(zip(objA, objB, {b: 2}), objC);
Опять же не все объекты вынес (`{b: 2}`), хочется единообразия в тестах. Но опять же если есть аргументы за такое решение, давай обсудим 

Посмотри внимательно еще раз везде, если будешь править

2022-02-12 11:46 UTC, Similization commented on tests/zip.js
> +		assert.deepEqual(zip(objA, objB, {b: 2}), objC);
Здесь скорее моя скупость на увеличение переменных, потому что объект `{b: 2}` является простым на мой взгляд и не требует создания аргумента под себя, но опять же это не проблема исправить, сейчас изменю.

Проглядел те "слитные" тесты, сейчас добавлю воздуха)

Комментарий по поводу выходных данных обдумал, согласен в целом, просто посмотрел комментарии у других ребят, решил, что лучше раньше перейти к данной теме, чтобы быстрее исправить, если необходимо.

2022-02-12 11:47 UTC, Similization commented on tests/zip.js
> +		const objA = {
В тех тестах, которые уже были даны названия тоже были упрощенные, да и не всегда скажем так есть идеи для абстрактных данных, где смог придумать - там изменил. Ладно, что-нибудь еще придумаю

2022-02-12 11:59 UTC, Similization commented on tests/zip.js
> +		assert.deepEqual(zip(objA, objB, {b: 2}), objC);
В тех тестах, что даны изначально, мне тоже добавить воздуха или не трогать их ?

2022-02-12 12:12 UTC, Similization commented on source/zip.js
> +*/
В данном случае описание явно относится к функции и как мне кажется является ее частью, я тоже люблю блочность, но в данном случае разделение лично мне не нравится, опять же на тех форумах, что смотрел - никто не разделял и это выглядит как-то целостнее что ли

2022-02-13 12:43 UTC, alexey-ershkov approved these changes

2022-02-13 12:43 UTC, alexey-ershkov commented on source/zip.js
> +*/
Хорошо, принимается

2022-02-14 15:07 UTC, Betchika99 requested changes
привет) рада видеть тебя на нашем курсе.

ментор привел тебя к интересному и лаконичному решению) оно правильное, но давай попробуем немного поменять алгоритм. попробуй реализовать алгоритм с использованием map, он будет немного сложнее, но зато ты попробуешь новую механику)

хочу позадавать тебе еще доп. вопросиков:
1) что такое spread-оператор и зачем ты его используешь?
2) какие типы данных могут выступать в качестве ключей объектов? как эти типы данных сравниваются между собой?

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-14 15:07 UTC, Betchika99 commented on source/zip.js
> +const zip = (...objects) => objects.reduce((prevObj, nextObj) => ({...nextObj, ...prevObj}), {});
давай все таки добавим валидацию, т.к. мы за более информативный клиент :) в мелких функциях обычно действительно достаточно сделать нужный вывод, но давай представим что мы реализуем реальную форму на сайте и должны показать хорошую человекочитаемую ошибку

2022-02-15 19:26 UTC, Similization commented on source/zip.js
> +const zip = (...objects) => objects.reduce((prevObj, nextObj) => ({...nextObj, ...prevObj}), {});
Добрый вечер

1) `...spread` я использую для превращения объекта типа `Object` в список полей и значений
Допустим у меня функция принимает список чисел (простейший Math.max) просто создать массив:
`let arr = [1, 2, 3]`
и передать его в ф-цию (Math.max(arr)) я не могу, но могу использовать `...spread`-оператор и с его помощью обратиться непосредственно к самим объектам массива:
`return Math.max(...arr)`   // вернет 3
`return Math.max(arr)`     // вернет NaN
2) Ключи объекта имеют тип строки или символа (`string`, `symbol`)
Символ более интересный тип, он не преобразуется автоматически в строку и каждый символ является уникальным. Например
`let id1 = Symbol("T-Rex")`
`let id2 = Symbol("T-Rex")`
`return id1 == id2`          // false
тем временем, как `id1.description` или `id2.description` вернет T-Rex

Сейчас map посмотрю

Добавил валидацию: на `null` или `undefined` - кидает alert и возвращает пустой объект

2022-02-16 11:32 UTC, closed without merging