Гуреев Никита, вариант 4
frontend-park-mail-ru/homework_2022_1 pull request #13
Opened 2022-02-07 19:28 UTC by Sitleman

2022-02-09 21:18 UTC, fillinmar reviewed
Поздравляю тебя с переходом на 2 семестр и приветствую на курсе фронтенда! Оставила комментарии по твоему решению. Удали, пожалуйста, все файлы, которые ты добавил, но в решении они не пригодились (.svg, .css) 
Если будут вопросы, то можешь писать в комменты или в [телеграм](https://telegram.me/fillinmar)

2022-02-09 21:18 UTC, fillinmar commented on source/inverse.js
> +const inverse = function(arr, arg = 0) {
Чаще всего в js для создания функции используют [стрелочные функции](https://learn.javascript.ru/arrow-functions-basics)

2022-02-09 21:18 UTC, fillinmar commented on source/inverse.js
> +/** @function inverse */
по jsdoc надо описывать еще параметры функции - их тип и их описание, а так же что они возвращают

2022-02-09 21:18 UTC, fillinmar commented on tests/inverse.js
> +	QUnit.test('Функция не работает с массивом четной длины', function (assert) {
она должна работать с массивом любой длины

2022-02-10 15:14 UTC, Sitleman commented on source/inverse.js
> +/** @function inverse */
Исправил

2022-02-10 15:47 UTC, fillinmar commented on source/inverse.js
> + * @param {obj[]} arr - Array of elements.
у тебя один из входных параметров - array, следовательно его и указывай в фигурных скобках

2022-02-10 16:52 UTC, Sitleman commented on source/inverse.js
> + * @param {obj[]} arr - Array of elements.
окей

2022-02-10 16:53 UTC, Sitleman commented on tests/inverse.js
> +	QUnit.test('Функция не работает с массивом четной длины', function (assert) {
Ахах
Наконец-то понял)
Исправил

2022-02-10 16:53 UTC, Sitleman commented on source/inverse.js
> + * @function inverse
Исправил

2022-02-10 16:54 UTC, Sitleman commented on tests/inverse.js
> +	QUnit.test('Функция не работает с массивом одинаковых элементов', function (assert) {
Да, исправил

2022-02-10 16:54 UTC, Sitleman commented on source/inverse.js
> +    return arr;
Окей, переделал

2022-02-10 17:21 UTC, fillinmar commented on source/inverse.js
> +    if (!Number.isInteger(arg) || !Array.isArray(arr)) return ['incorrect arguments'];
если введенные данные не верные, то лучше генерировать [исключения](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw)
и я бы сначала проверила первый аргумент, а потом уже второй

2022-02-10 17:21 UTC, fillinmar commented on source/inverse.js
> + * @function - Returns the invesed array except for the elements (from begin / to end) specified in the argument.
можно не указывать @function, а сразу писать что эта функция делает

2022-02-10 17:21 UTC, fillinmar commented on source/inverse.js
> +    return invArr;
можешь сразу возвращать arr.map, чтоб не создавать лишнюю переменную invArr

2022-02-10 17:37 UTC, Sitleman commented on source/inverse.js
> + * @function - Returns the invesed array except for the elements (from begin / to end) specified in the argument.
Исправил

2022-02-10 17:37 UTC, Sitleman commented on source/inverse.js
> +    return invArr;
Исправил

2022-02-10 17:52 UTC, fillinmar commented on source/inverse.js
> +        }
в js как и в других языках программирования есть [тернарный оператор](https://learn.javascript.ru/ifelse), использовать его здесь будет очень даже кстати

2022-02-10 18:56 UTC, Sitleman commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 1, 1, 1 ], 0), [ 1, 1, 1, 1 ]);
Добавил

2022-02-13 20:55 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

ты неплохо решил задачу, молодец :) есть несколько небольших замечаний и вопрос "на засыпку": расскажи кратко про способы разделения массива на N частей (например, пополам). всё, что знаешь :)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-13 20:55 UTC, Betchika99 commented on source/inverse.js
> + * @param {number} arg - Count of elements that don't need to be inversed.
посмотри повнимательнее документацию JSDoc, как там обозначаются опциональные параметры

2022-02-13 20:55 UTC, Betchika99 commented on source/inverse.js
> +    if (!Array.isArray(arr) || !Number.isInteger(arg)) {
если тебе случайно передали в arg строкой "2", то твоя функция вернет исключение. По сути это верно, но лучше делать код более гибким. Поэтому рекомендую перед проверкой isInteger приводить переменную к числовому типу явно

2022-02-13 20:55 UTC, Betchika99 commented on source/inverse.js
> + * @param {array} arr - Array of elements.
посмотри повнимательнее,[ как обозначается массив](https://jsdoc.app/tags-param.html) в JSDoc

2022-02-13 20:55 UTC, Betchika99 commented on source/inverse.js
> +        throw new Error("incorrect arguments :("); //Error: incorrect arguments';
лучше использовать во всем коде одинаковые кавычки. в данном случае одинарные. проверь по всему ДЗ (в тч тестах)

2022-02-13 20:55 UTC, Betchika99 commented on source/inverse.js
> +    let right = Math.min(arr.length + arg, arr.length);
почему ты здесь используешь `let`?

2022-02-13 20:55 UTC, Betchika99 commented on tests/inverse.js
> +		assert.throws(() => inverse([1, 2, 3], 'x'), err);
можно еще проверить null, объект и числовое значение, переданное строчкой (ex. "3")

2022-02-13 21:26 UTC, Sitleman commented on source/inverse.js
> +    let right = Math.min(arr.length + arg, arr.length);
Лучше объявить через const, так как не предполагается изменений этих переменных. Исправил

2022-02-13 21:59 UTC, Sitleman commented on tests/inverse.js
> +		assert.throws(() => inverse([1, 2, 3], 'x'), err);
Разделение массива на N частей:
1) C помощью двух вложенных циклов. Во внешнем итерируемся по подмассивам i = (0..N-1). Во внутреннем добавляем из исходного массива элементы в iй подмассив.
2) С помощью цикла и метода slice().
3) С помощью цикла и метода splice(). Только в данном случае будем все время брать элементы из начала массива, так как метод удаляет их в исходном массиве.
4) С помощью цикла и метода filter(). В условии filter задаем отбор по периоду индексов элементов, входящих в i подмассив. 
5) С помощью двух вложенных циклов и метода shift() или pop(), извлекая каждый раз элемент с края исходного массива в i подмассив.

2022-02-13 22:01 UTC, Sitleman commented
Готово

2022-02-14 12:30 UTC, Sitleman commented
> привет)) добро пожаловать на курс по Фронтенду))))
> 
> ты неплохо решил задачу, молодец :) есть несколько небольших замечаний и вопрос "на засыпку": расскажи кратко про способы разделения массива на N частей (например, пополам). всё, что знаешь :)
> 
> если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)
> 
> после того, как поправишь, напиши здесь коммент "Готово" плз :)

Готово

2022-02-14 12:32 UTC, Sitleman commented on tests/inverse.js
> +		assert.throws(() => inverse([1, 2, 3], 'x'), err);
Готово

2022-02-14 14:53 UTC, Betchika99 requested changes
последний рывок (я надеюсь)!

2022-02-14 14:53 UTC, Betchika99 commented on source/inverse.js
> +    arg = Number(arg);
попытка хорошая, но не надо изменять входные данные. лучше создать новую переменную

2022-02-15 07:12 UTC, Sitleman commented on source/inverse.js
> +    arg = Number(arg);
Готово

2022-02-15 17:06 UTC, closed without merging