First workable solution
frontend-park-mail-ru/homework_2022_1 pull request #14
Opened 2022-02-07 20:28 UTC by nezhibitskiy

2022-02-09 17:59 UTC, alexey-ershkov requested changes
Привет) Рад приветствовать тебя на курсе по Фронтенду) Поздравляю с переходом на второй семестр) Здесь будет круто, весело и полезно) Я буду проверять твою домашку) Отписал несколько комментов

Если будут вопросы - пиши в телегу @alexey_ershkov

2022-02-09 17:59 UTC, alexey-ershkov commented on source/inverse.js
> +'use strict';
Молодец, что используешь `use strict`, можешь рассказать, что это и зачем нужно?

2022-02-09 17:59 UTC, alexey-ershkov commented on source/inverse.js
> +const inverse = function (array, index = 0) {
Давай заиспользуем модные молодежные стрелочные функции) Расскажи в чем их принципиальное отличие от текущего использования? 

Плюс названия array и index очень общие - подумай над конкретизацией названий

2022-02-09 17:59 UTC, alexey-ershkov commented on source/max.js
> +const max = function (numbers) {
Эту функцию не нужно изменять - она пример

2022-02-09 17:59 UTC, alexey-ershkov commented on source/inverse.js
> +        array.reverse();
Дублирование кода - вынеси в функцию

2022-02-09 17:59 UTC, alexey-ershkov commented on tests/inverse.js
> +			assert.deepEqual(newArr[i], i);
Почему здесь для сравнения используешь deepEqual?

2022-02-09 17:59 UTC, alexey-ershkov commented on tests/inverse.js
> +	QUnit.test('Функция не обрабатывает большое количество данных', function (assert) {
Немного не понимаю смысл этого теста - можешь подробнее написать?

2022-02-09 17:59 UTC, alexey-ershkov commented on tests/inverse.js
> +	});
Давай добавим тестов на невалидные входные данные

2022-02-10 07:18 UTC, nezhibitskiy commented
Привет!)
Спасибо за поздравления!

2022-02-10 07:20 UTC, nezhibitskiy commented on source/inverse.js
> +'use strict';
Это строгий режим. Нужен для совместимости со старыми версиями JS. При использовании классов и модулей, строгий режим включается автоматически.

2022-02-10 07:23 UTC, nezhibitskiy commented on source/max.js
> +const max = function (numbers) {
Вернул прежнее значение. Я её менял для экспериментов и для того, чтобы разобраться полноценно в примере. Забыл потом обратно поменять)

2022-02-10 07:33 UTC, nezhibitskiy commented on source/inverse.js
> +const inverse = function (array, index = 0) {
Стрелочные функции, во первых, имеют более компактный синтаксис, а, во вторых, стрелочные функции исходно анонимные (если не записать их в переменную).

2022-02-10 07:47 UTC, nezhibitskiy commented on tests/inverse.js
> +			assert.deepEqual(newArr[i], i);
Мы сравниваем данные по значению, а не на то, являются ли данные одним и тем же объектом

2022-02-10 07:56 UTC, nezhibitskiy commented on source/inverse.js
> +    /** Check if index is default */
Их всего 8: число, большое число, строка, двоичная единица, null, undefined, объекты и символы.

2022-02-10 07:57 UTC, nezhibitskiy commented on tests/inverse.js
> +	QUnit.test('Функция не обрабатывает большое количество данных', function (assert) {
Исправил описание. Мини стресс тест) (не сломается ли функция, если будет много входных данных)

2022-02-10 14:28 UTC, alexey-ershkov commented on source/max.js
> +const max = function (numbers) {
Похвальное стремление) Лайк

2022-02-10 14:35 UTC, alexey-ershkov requested changes
Хорошая работа) Осталось немного - отписал еще немного комментов

2022-02-10 14:35 UTC, alexey-ershkov commented on source/inverse.js
> +        let unchangalbeArrPart = inputArray.splice(0, offsetIndex);
Почему используешь здесь `let`, а не `const`? В чем их различие?

2022-02-10 14:35 UTC, alexey-ershkov commented on source/inverse.js
> + * @param {number} offsetIndex - Index of unchangeable part of array (if negative, counts from end of array)
JSDoc позволяет добавить примеры и описать возвращаемое значение, давай добавим эти параметры

2022-02-10 14:35 UTC, alexey-ershkov commented on tests/inverse.js
> +	QUnit.test('Функция не обрабатывает большое количество входных данных (>10^3)', function (assert) {
А в чем проблема обработать большое количество данных? С какими ограничениями сталкиваешься?

2022-02-10 15:03 UTC, nezhibitskiy commented on source/inverse.js
> +        let unchangalbeArrPart = inputArray.splice(0, offsetIndex);
let - это переменная, а const - константа. Константу после объявления нельзя изменить

2022-02-10 15:04 UTC, nezhibitskiy commented on tests/inverse.js
> +	QUnit.test('Функция не обрабатывает большое количество входных данных (>10^3)', function (assert) {
Ну если рассматривать тестирование "черного ящика", то этот тест необходим. Вдруг у нас там куча if условий, которые работают только с определенным количеством данных

2022-02-10 15:10 UTC, nezhibitskiy commented on source/inverse.js
> +        let unchangalbeArrPart = inputArray.splice(0, offsetIndex);
Поменял на const, так как мы не изменяем эту переменную)

2022-02-11 18:23 UTC, alexey-ershkov commented on tests/inverse.js
> +	QUnit.test('Функция не обрабатывает большое количество входных данных (>10^3)', function (assert) {
Тогда получается нужно назвать тест, что функция обрабатывает большое количество данных - меня смущается "не" в названии теста

2022-02-11 18:27 UTC, alexey-ershkov requested changes
Еще немного комментов

2022-02-11 18:27 UTC, alexey-ershkov commented on source/inverse.js
> + * @param {number} offsetIndex - Index of unchangeable part of array (if negative, counts from end of array)
Возвращаемое значение все еще не описано - можешь  почитать подробнее [здесь](https://jsdoc.app/tags-returns.html)

2022-02-11 18:27 UTC, alexey-ershkov commented on source/inverse.js
>      else
Давай избавимся от else - логично, что если мы дойдем до кода после `if`, то `offsetIndex < 0` 

А из-за else получается лишняя вложенность

2022-02-11 18:56 UTC, nezhibitskiy commented on source/inverse.js
>      else
Окей)

2022-02-11 19:00 UTC, nezhibitskiy commented on source/inverse.js
> + * @param {number} offsetIndex - Index of unchangeable part of array (if negative, counts from end of array)
Прости, я когда вносил исправления, примеры добавил, а про возвращаемое значение забыл. Внес изменения в последнем коммите

2022-02-12 08:34 UTC, alexey-ershkov approved these changes

2022-02-12 10:51 UTC, alexey-ershkov requested changes
Нашел еще несколько моментов

2022-02-12 10:51 UTC, alexey-ershkov commented on source/inverse.js
> +    if (!inputArray) return inputArray;
Это не очень логичное поведение кода - давай здесь выбрасывать ошибку.  Какие виды ошибок есть в JavaScript? Какая подойдет сюда? 

Кстати - что будет если в качестве `inputArray` передать `true`?  Кажется есть смысл изменить проверку

2022-02-12 10:51 UTC, alexey-ershkov commented on source/inverse.js
> +const inverse = (inputArray, offsetIndex = 0) => {
Давай разделим пустой строкой JSDoc и саму функцию - это даст "воздуха" коду

2022-02-12 10:51 UTC, alexey-ershkov commented on tests/inverse.js
> +		assert.deepEqual(inverse(null, null), null);
И соответсвенно здесь поправить тесты, на то, что выбрасывается ошибка в случае невалидных данных

2022-02-12 10:51 UTC, alexey-ershkov commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], null), [ 5, 4, 3, 2, 1 ]);
Это не оч логично - невалидные данные подразумевают - что функция не может работать с такими данными,  а здесь в целом ожидаемое поведение и функция спокойно делает inverse

так что лучше докинуть еще тестов на то, что не сможет обработать функция

2022-02-12 12:43 UTC, alexey-ershkov approved these changes

2022-02-15 15:38 UTC, Betchika99 approved these changes

2022-02-15 15:38 UTC, closed without merging