Variant 7
frontend-park-mail-ru/homework_2022_1 pull request #17
Opened 2022-02-08 08:08 UTC by iiivan-lemon

Необходимо было написать функцию plain, которая будет принимать на вход массив массивов и создавать из них один общий массив. Массивы могут быть любой вложенности.
Также необходимо было написать несколько доп. тестов и описание 1jsdoc

Сафронов Иван WEB-21

2022-02-09 15:37 UTC, dnlipko requested changes

2022-02-09 15:37 UTC, dnlipko commented on source/plain.js
> +const plain = arr => arr.flat(Infinity);
Хорошо, что ты разузнал про `flat`. Но тут легко не отделаешься. Сделай собственную реализацию без использования `flat` чтобы лучше ознакомится с возможностями js

2022-02-10 06:13 UTC, dnlipko requested changes

2022-02-10 06:13 UTC, dnlipko commented on source/plain.js
> +    for (let i = 0; i < arr.length; ++i) {
Если при итерирации по массиву накапливается новое значение, то хорошо подходит `reduce`
[способs итерации](https://learn.javascript.ru/array-iteration)

2022-02-10 06:13 UTC, dnlipko commented on source/plain.js
> +    for (let i = 0; i < arr.length; ++i) {
Тогда можно получить стрелочную функцию вида `const plain = arr => arr.reduce();`

2022-02-10 06:13 UTC, dnlipko commented on source/plain.js
> +        if (Array.isArray(arr[i])) {
Тут можно воспользоваться [тернарным оператором](https://learn.javascript.ru/ifelse) из нового стандарта и дальше может пригодится [спред оператор](https://learn.javascript.ru/rest-parameters-spread-operator)

2022-02-13 21:23 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

ты очень здорово (дважды) решил задачу, молодец :) есть несколько комментов небольших и вопрос "на засыпку": ты использовал concat для объединения массивов, а знаешь ли ты про другие способы "склеить" массивы? расскажи про них кратко.

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-13 21:23 UTC, Betchika99 commented on source/plain.js
> +const plain = arr => {
для удобства читаемости параметры функции обычно оборачивают в круглые скобки ()

2022-02-13 21:23 UTC, Betchika99 commented on source/plain.js
> +    return Array.isArray(arr) ? arr.reduce((arrMerg, curr) => arrMerg.concat(plain(curr)), []) : arr;
очень лаконичное решение, почти как просто использование flat :) 
обычно использование рекурсивных алгоритмов на клиенте = какая-то неверная логика работы всего сервиса (т.к. это одна из самых супер дорогих операций, замедляющих клиента). Постарайся переписать алгоритм без рекурсии

2022-02-13 21:23 UTC, Betchika99 commented on tests/plain.js
> +	});
давай добавим тестов на невалидные входные данные

2022-02-14 12:45 UTC, iiivan-lemon commented
Привет!
объединить массивы можно с пом. 
спред оператора a3 = [...a1, ...a2] элементы идут в том порядке, в котором идут переменные массивов
a1.push(...a2) через пуш и спред можно в сущ. массив добавить другой массив

2022-02-14 12:46 UTC, iiivan-lemon commented on source/plain.js
> +const plain = arr => {
добавил

2022-02-14 13:50 UTC, iiivan-lemon commented on source/plain.js
> +    return Array.isArray(arr) ? arr.reduce((arrMerg, curr) => arrMerg.concat(plain(curr)), []) : arr;
убрал рекурсию, использую буфер в виде стека

2022-02-14 13:53 UTC, iiivan-lemon commented on tests/plain.js
> +	});
добавил тесты, на вход которых принимается не массив

2022-02-14 14:07 UTC, iiivan-lemon commented
Готово

2022-02-15 16:18 UTC, closed without merging