Task done
frontend-park-mail-ru/homework_2022_1 pull request #18
Opened 2022-02-08 11:51 UTC by petrenkilya

Петренко Илья

2022-02-09 16:02 UTC, dnlipko commented on source/chess.js
> +    for (let i = 0; i < inputSize; i++) {
В js нет `range N`, но из-за большой не любви к `for` иногда используют  `Array.from(Array(3)).forEach` или `[...Array(N)].forEach` https://stackoverflow.com/questions/10993824/do-something-n-times-declarative-syntax

2022-02-09 16:03 UTC, dnlipko commented on source/chess.js
> +    strWithBegin += "\n";
[Шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals) подойдут идеально

2022-02-09 16:04 UTC, dnlipko commented on source/chess.js
> +        if (i % 2) {
[Тернарный оператор](https://learn.javascript.ru/ifelse) сделает код более компактным

2022-02-09 16:15 UTC, dnlipko commented on source/chess.js
> +'use strict';
Переименуй ПР в формат `Фамилия Имя Вариант N`

2022-02-11 08:19 UTC, petrenkilya commented on source/chess.js
> +    for (let i = 0; i < inputSize; i++) {
Просмотрел эту статью, не понял какой метод подходит лучше, если только Array.from(Array(3)).forEach, но разве стоит городить такую конструкции ради ухода от простого for?

2022-02-11 08:20 UTC, petrenkilya commented on source/chess.js
> +    strWithBegin += "\n";
Прочитал, не понял как они в этой задаче пригодятся

2022-02-11 09:30 UTC, dnlipko requested changes

2022-02-11 09:30 UTC, dnlipko commented on source/chess.js
> +    Array.from(Array(size)).forEach((iter, index) => {
Если ты итерируешься по массиву и накапливаешь одно значение то подходит `reduce`
return Array.from(Array(size)).reduce((outputStr, _, index) => `${outputStr}${(index % 2) ? strWithoutBegin : strWithBegin}`
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

Но можно и без цикла обойтись
Известно что строчки идут парой 
Нужно size/2 раз повторить `${strWithoutBegin}${strWithBegin}`
И добавить size%2 strWithoutBegin

Тут пригодится https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

2022-02-11 09:30 UTC, dnlipko commented on source/chess.js
> +    strWithoutBegin += "\n";
Можно не делать присваивания здесь, а использовать шаблонные строки в месте где необходимо добавить \n

2022-02-11 09:30 UTC, dnlipko commented on source/chess.js
> +    for (let i = 0; i < size; i++) {
Давай тут избавимся от цикла

strWithoutBegin = size/2 раз '* '  + size%2 раз '*'
Аналогично для strWithBegin

И можно это вынести в отдельный метод

 const treeLine = (size, ...) => `${size/2 раз '* ' }${size%2 раз '*'}\n`

2022-02-11 10:42 UTC, dnlipko requested changes

2022-02-11 10:42 UTC, dnlipko commented on source/chess.js
> +    let strWithBegin = '* '.repeat(size/2).concat((size % 2) ? '*\n' : '\n');
const ?

2022-02-11 10:42 UTC, dnlipko commented on source/chess.js
> +    let strWithBegin = '* '.repeat(size/2).concat((size % 2) ? '*\n' : '\n');
size %2 три раза вижу в коде

2022-02-11 10:42 UTC, dnlipko commented on source/chess.js
> +    let strWithoutBegin = ' *'.repeat(size/2).concat((size % 2) ? ' \n' : '\n');
Я давно уже не видел конкат потому что есть шаблонные строки. Давай все таки воспользуемся ими)
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2022-02-11 10:42 UTC, dnlipko commented on source/chess.js
> +    let outputStr = `${strWithBegin}${strWithoutBegin}`.repeat(size/2).concat((size % 2) ? strWithBegin : "");
Чейнинг можно записать по лучше 

````
return str
  .repeat()
  .concat()
````

2022-02-11 10:42 UTC, dnlipko commented on source/chess.js
> +    let strWithoutBegin = ' *'.repeat(size/2).concat((size % 2) ? ' \n' : '\n');
`${' *'.repeat(size/2)}${size%2 ? ' ' : '')}\n`

2022-02-11 10:42 UTC, dnlipko commented on source/chess.js
> +    let outputStr = `${strWithBegin}${strWithoutBegin}`.repeat(size/2).concat((size % 2) ? strWithBegin : "");
Эта строчка очень похожа на 
let strWithoutBegin = ' *'.repeat(size/2).concat((size % 2) ? ' \n' : '\n');

`${line.repeat(N)}${flag ? ending : ''}\n`
Можно и в отдельный метод вынести)

2022-02-11 11:37 UTC, dnlipko commented on source/chess.js
> +    const strWithoutBegin = generateRepeatedStr(' *', repeatedNum, (endingNeeded) ? ' ' : '');
В теранрном операторе можно не использовать круглые скобки вокруг условия

2022-02-11 11:40 UTC, dnlipko commented on source/chess.js
> +    const endingNeeded = size % 2;
Переменный с bool значением часто называют с использованием is
`isEndingNeeded`

2022-02-15 13:37 UTC, closed without merging