Денисова Настя 5 вариант
frontend-park-mail-ru/homework_2022_1 pull request #2
Opened 2022-02-05 15:31 UTC by antdenv

2022-02-07 16:08 UTC, Tataklim commented
Привет! Рада тебя приветствовать на курсе фронтенда :)
Я буду проверять твое дз - если будут какие-то вопросы, с радостью отвечу)

2022-02-07 16:13 UTC, Tataklim commented on source/chess.js
> +const chess = function(size) {
Расскажи, сколько способов объявления функций в js ты уже знаешь?) Может, можно попробовать на что-то заменить текущий вариант?)

2022-02-07 16:13 UTC, Tataklim commented on tests/chess.js
> +	});
А что если не число?) Давай такой вариант тоже обработаешь и напишешь к нему тестик?

2022-02-07 16:13 UTC, Tataklim commented on source/chess.js
> +    if(size == 1 || size == 0) return null;
Предлагаю почитать [правила](https://learn.javascript.ru/coding-style) оформления кода в js и исходя из прочитанного попробовать что-то поправить)

2022-02-07 16:13 UTC, Tataklim commented on source/chess.js
> +};
Попробуй узнать, для чего принято в конец файла добавлять пустую строку)

2022-02-07 16:13 UTC, Tataklim commented on source/chess.js
> +    for(let i = 0; i < size; i++) result += (i % 2 ? ' *' : '* ').repeat(Math.floor(size / 2) + 1).slice(0, size % 2 - 2) + '\n';
Код в одну строку сложно понимается - попробуй красивенько разнести на несколько строк

2022-02-07 16:13 UTC, Tataklim commented on source/chess.js
> +const chess = function(size) {
Попробуй добавить своей функции [JSDoc](https://jsdoc.app/) - этот ресурс документирования кода

2022-02-07 16:42 UTC, antdenv commented on source/chess.js
> +const chess = function(size) {
1) Function Declaration (Объявление функции)
function name(parameters) {
    body
}

2) Function Expression (Функциональное выражение)
let variableName = function(parameters) {
    body
};

3) Стрелочная функция
let variableName = (parameters) => {
    body
};

Думаю, можно заменить мой вариант на стрелочную функцию, так будет выглядеть короче

2022-02-07 17:28 UTC, Tataklim commented on source/chess.js
> +const chess = function(size) {
Помимо краткости какие еще особенности у стрелочной функции?)

2022-02-07 17:40 UTC, antdenv commented on source/chess.js
> +const chess = function(size) {
У стрелочных функций, как и у функциональных выражений есть такая особенность: так как мы даём имя функции путем определения переменной, если мы будем использовать ключевое слово const при определении, то исключается возможность перезаписи данной переменной. В функции определении мы можем перезаписать переменную name. 
Также такие функции удобны, когда нам нужно использовать функцию как коллбэк-функцию (такие функции также называются анонимными, поэтому в качестве аргумента мы можем просто передавать такие функции).
Надеюсь, правильно объяснила :)

2022-02-07 20:23 UTC, Tataklim commented on source/chess.js
> +const chess = function(size) {
Объяснила все отлично!
Сможешь объяснить, почему их именно в качестве коллбэка удобно использовать?

2022-02-07 21:08 UTC, antdenv commented on source/chess.js
> +const chess = function(size) {
1) Нам не нужно заранее определять какую-либо функцию вне функции, которая в качестве аргумента принимает коллбэк-функцию и писать ее имя потом в аргументах, мы в аргументах можем сразу определить функцию как стрелочную функцию.

ПРИМЕР:
// Использование стрелочных функций
setTimeout(() => console.log("Hello from arrow function!"), 1000);

// Использование обычной функции для получения
// того же функционала
function sayHello() {
    console.log("Hello from function declaration!");
}
setTimeout(sayHello, 1000);

2) Стрелочная функция не имеет своего "this", то есть, если мы в объектах определяем какой-нибудь метод и хотим в этом методе обращаться к этому объекту, то используя стрелочные функции и обращаясь внутри нее к объекту через ключевое слово this, в качестве this будет использоваться тот объект, что вызывает этот метод. Если мы будем использовать обычное определение функции, у нас ничего не получится, так как обычная функция будет использовать в качестве this либо объект window, либо undefined.

ПРИМЕР:
// Использование стрелочной функции
let object = {
    name: 'Nastya',
    sayHello: function() {
        // В качестве коллбэка для setTimeout() используем стрелочную функцию
        setTimeout(() => console.log(`Hello, ${this.name}!`), 1000);
    }
};
object.sayHello(); // Hello, Nastya!

// Использование обычной функции
let object2 = {
    name: 'Nastya',
    sayHello: function() {
        // В качестве колбэка для setTimeout() используем обычную функцию
        setTimeout(function() {
            console.log(`Hello, ${this.name}!`)
        }, 1000);
    }
};
object2.sayHello(); // Hello, undefined!

2022-02-08 12:01 UTC, antdenv commented on source/chess.js
> +const chess = function(size) {
Остальные все замечания тоже подправила)

2022-02-08 17:26 UTC, Tataklim commented on source/chess.js
> +const chess = function(size) {
Прекрасно объяснила!

2022-02-08 17:27 UTC, Tataklim commented on tests/chess.js
> +	QUnit.test('Невалидные данные для построения шахматной доски', function(assert) {
Кажется, можно объединить этот и предыдущий тестик
Также добавь, пожалуйста, побольше невалидных параметров

2022-02-08 18:12 UTC, antdenv commented on tests/chess.js
> +	QUnit.test('Невалидные данные для построения шахматной доски', function(assert) {
Исправила и добавила)

2022-02-08 20:32 UTC, Tataklim commented on tests/chess.js
> +		assert.strictEqual(chess(5.2), null);
Эхх, есть еще отрицательные числа - как с ними быть?))

2022-02-08 21:03 UTC, antdenv commented on tests/chess.js
> +		assert.strictEqual(chess(5.2), null);
Добавила) и еще null и object

2022-02-08 21:39 UTC, Tataklim commented
Спасибо за твои подробные объяснения и быстрые исправления!
Мне все ок, передаю твою домашку дальше :)

2022-02-10 22:11 UTC, Betchika99 requested changes
привет)) рада видеть тебя на курсе по Фронтенду))))

- [ ]  твое решение корректное, но есть несколько небольших замечаний по его оптимальности
- [ ]  подумай внимательнее про тесты, пока у тебя много избыточных проверок там

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

p.s. вопрос "на засыпку". подумай, как можно решить твою задачу без цикла for. Какие методы языка можно использовать? можешь не реализовывать, а просто рассказать алгоритм и что ты бы использовала

2022-02-10 22:11 UTC, Betchika99 commented on source/chess.js
> +                  .repeat(Math.floor(size / 2) + 1)
почему на каждой итерации нужно высчитывать значение `(Math.floor(size / 2) + 1)`? оно же не меняется => это лишняя дорогая операция (и на следующей строке тоже)

2022-02-10 22:11 UTC, Betchika99 commented on source/chess.js
> +                  .slice(0, size % 2 - 2) + '\n';
давай воспользуемся конкатенацией строк через шаблонные строки. подробнее можешь почитать [здесь](https://dev-gang.ru/article/-sposoba-obedinenija-strok-v-javascript-prgtacj4yl/)

2022-02-10 22:11 UTC, Betchika99 commented on tests/chess.js
> +	});
чем эти тесты отличаются от уже написанного 8х8, 3х3 и т.п. ?

2022-02-10 22:11 UTC, Betchika99 commented on tests/chess.js
> +		assert.strictEqual(chess('-10'), null);
почему бы не сделать эти проверки в цикле?) и убрать избыточные варианты

2022-02-10 22:11 UTC, Betchika99 commented on tests/chess.js
> +	});
нет проверки на undefined или массив. поизучай типы данных и проверь их здесь)

2022-02-14 10:49 UTC, antdenv commented on tests/chess.js
> +	});
Исправила замечания)

2022-02-14 14:32 UTC, Betchika99 requested changes
остался один (надеюсь, последний) коммент :)

2022-02-14 20:53 UTC, antdenv commented on source/chess.js
> +    let sliceUpperLimit = size % 2 - 2;
Да, ошиблась)
Исправила

2022-02-15 17:05 UTC, closed without merging