Голубев Сергей Вариант 3
frontend-park-mail-ru/homework_2022_1 pull request #20
Opened 2022-02-08 17:34 UTC by yutfut

2022-02-08 17:42 UTC, SPetrenko17 commented
Велком ту де клаб бадди! Я протягиваю тебе две таблетки. Если выберешь красную, то ты будешь шарить за фронтенд. Если выберешь синюю, то тебя отчислят. Выбор за тобой... А так, я приветствую тебя на топ-семе тп!
ПЫ.СЫ. Я ментор Сережа и я ща буду ревьюить тебя...

2022-02-08 17:45 UTC, SPetrenko17 commented on source/roman.js
> +function roman(input_number) {
Знаешь ли ты разницу между стрелочной функцией и функцией объявленной с помощью function?
Сможешь сделать так, чтобы здесь были красивые стрелочные функции?

2022-02-08 17:46 UTC, SPetrenko17 commented on source/roman.js
> +        return(int_to_roman(input_number));
Мистер линтер негодует. А еще он очень любит camelCase в JS... Го поправим везде)

2022-02-08 17:48 UTC, SPetrenko17 commented on source/roman.js
> +        if (roman_to_int[input_number[i]] < roman_to_int[input_number[i+1]])
Мистер линтер вернулся с пакетом фигурных скобок...

2022-02-08 17:48 UTC, SPetrenko17 commented on source/roman.js
> +        if (roman_to_int[input_number[i]] < roman_to_int[input_number[i+1]])
А еще убедись, что else необходим. Так меньше кода будет)

2022-02-08 17:49 UTC, SPetrenko17 commented on tests/test_roman.js
> +    QUnit.test('даги в москве', function (assert) {
Го норм название добавим... А то мистер Линтер и преподы отчислят)

2022-02-08 17:50 UTC, SPetrenko17 commented on tests/test_roman.js
> +    QUnit.test('даги не в москве', function (assert) {
Добавь тесты с проверкой на невалидные данные

2022-02-09 16:34 UTC, SPetrenko17 commented on source/roman.js
> +const int_to_roman = (inputNumber) => {
Пропустил кэмлкейс

2022-02-09 16:35 UTC, SPetrenko17 commented on source/roman.js
> +const isNumber = (n) => {
Добавь JSDoc для всех функций

2022-02-09 16:36 UTC, SPetrenko17 commented on source/roman.js
> +const roman_to_int = (inputNumber) => {
Предлагаю добавить валидацию типов для всех функций

2022-02-09 16:38 UTC, SPetrenko17 commented on source/roman.js
> +const int_to_roman = (inputNumber) => {
А еще давай не будем редактировать значения снаружи. Создай копию, с которой будешь работать

2022-02-10 13:42 UTC, SPetrenko17 commented on source/roman.js
> +    const dictIntToRoman = {
Го вынесем наружу эти dict.
Кстати, можно попробовать второй dict собрать из первого

2022-02-10 19:58 UTC, SPetrenko17 commented on source/roman.js
> +const objectFlip = (obj) => {
B повыше вынеси

2022-02-14 13:59 UTC, Betchika99 requested changes
привет) добро пожаловать на курс)

довольно не плохое решение. Посмотри внимательно комментарии и постарайся максимально использовать конструкции языка JS (а не си!), чтобы код стал симпатичнее. Также есть некоторые вопросы (см. в замечаниях)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +    return ret;
кажется, здесь отлично подойдет метод массивов reduce, попробуй его использовать для накопления ret. И давай назовем эту переменную более информативно :)

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> + * @param {number|string} inputNumber - число в римской или десятичной системе сичсления.
опечатка

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +}
не очень нравится такая вложенная структура. можно гораздо чище это написать.
во-первых, если ты делаешь return из if-блока, не надо дальше использовать else (ты и так пойдешь дальше по коду при невыполнении условия).
во-вторых, давай переместим проверку на невалидные данные в начало функции

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +            return(convertIntToRoman(parseInt(inputNumber)));
какие есть еще способы преобразовать строку в число в JS?

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +const isNumber = (checkingString) => {
расскажи, а почему вместо этой функции не использовать build-in проверку !isNaN например?

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +    return !isNaN(parseFloat(checkingString)) && !isNaN(checkingString - 0)
зачем вычитать 0? =)

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +    return res;
кажется, здесь тоже лучше использовать reduce)))

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +    let buffInputNumber = inputNumber.toUpperCase();
почему здесь используется `let`?

2022-02-14 13:59 UTC, Betchika99 commented on source/roman.js
> +    return res;
и даже здесь можно reduce :))

2022-02-15 20:30 UTC, closed without merging