Иванов Виктор, вариант 7
frontend-park-mail-ru/homework_2022_1 pull request #22
Opened 2022-02-08 20:11 UTC by Victorius19

2022-02-09 22:09 UTC, nathanKith commented
Привет и добро пожаловать на курс фронтенда :) Я с удовольствием сейчас буду проверять твою домашку, ведь тебе попалась моя любимая задачка. 
А ты напиши, пожалуйста, ниже свою телегу, чтобы мы могли если что связаться)

2022-02-09 22:14 UTC, nathanKith commented on tests/plain.js
> +	});
Вижу тесты - жму руку семь раз.

2022-02-09 22:14 UTC, nathanKith commented on source/plain.js
> +'use strict';
Такс, а объяснишь мне плиз что такое strict и зачем он вообще нужен?

2022-02-09 22:14 UTC, nathanKith commented on source/plain.js
> +const plain = arr => arr.flat(Infinity);
Краткость - сестра таланта. Это правда, фронтендеры любят писать все покороче :))
Но я в первую очередь попрошу тебя написать решение более алгоритмическое (т.е. без использования метода flat, все остальные методы массивов юзай на здоровье)

Задачка на самом деле классическая, и мне лично дважды попадалась на собесах. Так что будет полезно уметь ее решать :)

2022-02-09 22:14 UTC, nathanKith commented on source/plain.js
> +const plain = arr => arr.flat(Infinity);
кстати, за стрелочную функцию готов пожать руку восьмой раз, НО
Обособляй аргументы стрелочной функции в скобки ВСЕГДА. Даже если аргумент один. Это хороший паттерн, улучшает читаемость кода.

2022-02-09 22:14 UTC, nathanKith commented on source/plain.js
> +const plain = arr => arr.flat(Infinity);
За const, кстати, девятый раз жму руку

2022-02-10 20:54 UTC, Victorius19 commented on source/plain.js
> +'use strict';
Это строгий режим. Добавил, чтобы движок понимал, что могут использоваться новые возможности языка

2022-02-10 21:04 UTC, Victorius19 commented on source/plain.js
> +    return arr.reduce((acc, el) => Array.isArray(el) ? [...acc, ...plain(el)] : [...acc, el], []);
Если у рекурсии будет слишком большая глубина, она может переполнить стек и выполнение прервется.

2022-02-10 21:18 UTC, nathanKith commented on source/plain.js
> +const plain = (arr) => {
Такс, а как еще можно объявить функцию в js? Сколько есть видов объявления?

2022-02-10 21:20 UTC, nathanKith commented on source/plain.js
> +    return arr.reduce((acc, el) => Array.isArray(el) ? [...acc, ...plain(el)] : [...acc, el], []);
Это можно не кодить, просто вопрос. Есть идеи как бороться с переполнением стека на примере конкретно этой задачи?

2022-02-10 21:44 UTC, Victorius19 commented on source/plain.js
> +const plain = (arr) => {
Думаю, что единственный способ, это отказаться от рекурсии в решении. Т.к. любую рекурсию можно записать в виде обычной функции, то эту задачу тоже можно решить без рекурсии.
Не уверен, что моя идея оптимальна. Но я попробовал бы обходить массив и на каждом элементе либо "проваливаться" на уровень в верх, либо возвращаться на уровень вниз (если очередной массив кончается). После обработки каждого элемента требовалось бы либо удалять его, либо хранить в отдельном месте его позицию. Каждый ход записывать все собранные цифры в новый массив, который надо будет вернуть после выполнения.

2022-02-15 13:22 UTC, Betchika99 requested changes
привет) добро пожаловать на курс по Фронтенду)

у тебя очень красивое и лаконичное решение, молодец! Есть только один комментарий на него :)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как поправишь, лучше тоже напиши в тг.

2022-02-15 13:22 UTC, Betchika99 commented on source/plain.js
> +    return arr.reduce((acc, el) => Array.isArray(el) ? [...acc, ...plain(el)] : [...acc, el], []);
давай все-таки реализуем алгоритм без рекурсии. Рекурсия на клиенте = проблема в архитектуре. Такие проблемы сложно мониторить

2022-02-15 19:14 UTC, Victorius19 commented on source/plain.js
> +    return arr.reduce((acc, el) => Array.isArray(el) ? [...acc, ...plain(el)] : [...acc, el], []);
Реализовал алгоритм без рекурсии

2022-02-15 19:23 UTC, closed without merging