Найденов Александр, Вариант 2
frontend-park-mail-ru/homework_2022_1 pull request #24
Opened 2022-02-08 20:46 UTC by yalublukotikov

2022-02-10 08:59 UTC, Shureks-den commented
Привет! Поздравляю с поступление на курс фронтенда. Меня зовут Александр и я буду проверять твое дз. Если я долго не отвечаю, а замечания ты поправил, то можешь написать мне в телегу https://t.me/alexklonov

2022-02-10 09:09 UTC, Shureks-den requested changes

2022-02-10 09:09 UTC, Shureks-den commented on index.html
>  <script src="source/max.js"></script>
Ненужные тесты и функцию max можно удалить чтобы не мешалась

2022-02-10 09:09 UTC, Shureks-den commented on source/euclid.js
> +'use strict';
Вижу, что ты используешь 'строгий' режим. Расскажи для чего и какие преимущества(или недостатки) он предоставляет в отличие от 'нестрогого' режима

2022-02-10 09:09 UTC, Shureks-den commented on source/euclid.js
> + * @param {...numbers} - input array of natural numbers.
Круто, что используешь jsdoc, он может реально сэкономить время в больших проектах. Только мне кажется param должен быть ...number, но это так придирка)

2022-02-10 09:09 UTC, Shureks-den commented on source/euclid.js
> +const euclid = function(...numbers){
Вопрос по способам созданий функций. Какие способы создания функций ты знаешь, в чем между ними разница? Какой способ ты используешь здесь?

2022-02-10 09:09 UTC, Shureks-den commented on source/euclid.js
> +   for (let i = 1; i < numbers.length; i++){
Решение хорошее, но я словил флешбэк с плюсов :( Можно сделать красивее и с меньшим числом циклов. Прочитай про метод reduce у массива, он как раз тут идеально подходит

2022-02-10 09:09 UTC, Shureks-den commented on tests/euclid.js
> +
Круто, что написал тесты!

2022-02-10 09:11 UTC, Shureks-den commented on source/euclid.js
> +   for (let i = 1; i < numbers.length; i++){
И еще один классический вопрос - расскажи про const, let, var и их отличия между собой и почему тут ты используешь, что используешь

2022-02-10 13:56 UTC, yalublukotikov commented on source/euclid.js
> +'use strict';
Строгий режим преобразует некоторые ошибки, которые раньше пропускались JS, в исключения, помогает движку оптимизировать код для более быстрого выполнения, а также запрещает использовать некоторые элементы синтаксиса

2022-02-10 14:06 UTC, yalublukotikov commented on source/euclid.js
> +const euclid = function(...numbers){
Можно использовать Function Declaration, Function Expression или создать стрелочную функцию. Первый способ - функция объявляется отдельной конструкцией в коде. Второй способ - функция создается внутри другого выражения. Разница в них в следующем: функции, объявленные заранее, то есть с помощью function declaration, мы можем использовать во всем коде, то есть при выполнении скрипта движок заранее определяет такие функции, что разрешает пользователю использовать функции до их определения. Функции, созданные с помощью function expression, создаются, когда выполнение скрипта доходит до них, и только после этого они могут использоваться. Также есть стрелочные функции, которые более краткие и простые, чем function expression. Здесь я использую второй метод, а именно - function expression.

2022-02-10 15:05 UTC, yalublukotikov commented on source/euclid.js
> +   for (let i = 1; i < numbers.length; i++){
Исправил решение с методом reduce. Прошу проверить

2022-02-10 15:09 UTC, Shureks-den commented on source/euclid.js
> +        let y = b;
Зачем эта строка, можно же просто b везде юзать или в качестве параметра функции y написать

2022-02-10 15:11 UTC, Shureks-den commented on source/euclid.js
> +        x += y;
Можно просто сделать return x + y

2022-02-10 15:13 UTC, Shureks-den commented on source/euclid.js
> +        let y = b;
x тоже можно убрать кстати

2022-02-10 20:51 UTC, yalublukotikov commented on source/euclid.js
> +        x += y;
Все исправил

2022-02-10 20:54 UTC, Shureks-den approved these changes

2022-02-14 13:18 UTC, Betchika99 requested changes
привет) добро пожаловать на курс)

молодец, что попробовал решить задачу с использованием современного JS. есть небольшие замечания и вопрос: какие способы итерирования по массиву в JS ты знаешь (кратко)? и почему в твоей задаче лучше всего подошел reduce?

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-14 13:18 UTC, Betchika99 commented on source/euclid.js
> +   let result = numbers.reduce(function(x, y) {
можно обойтись без этой переменной и сразу вернуть из функции результат reduce

2022-02-14 13:18 UTC, Betchika99 commented on source/euclid.js
> +        while (x && y){
перед фигурной скобкой нужен пробел

2022-02-14 14:35 UTC, yalublukotikov commented on source/euclid.js
> +   return result;
Можно итерироваться по массиву с помощью метода forEach - он для каждого элемента использует функцию callback. Можно итерироваться с помощью цикла for, как в плюсах, можно использовать циклы for ... in, for ... of. Можно перебрать массив с использованием цикла while и итератора. Также можно использовать reduce, что я и сделал при решении задачи, потому что reduce позволяет обработать все элементы массива с сохранением промежуточного результата.

2022-02-14 14:42 UTC, yalublukotikov commented on source/euclid.js
> +   return result;
Не особо привычно видеть такие функции после плюсов, поэтому для меня в новинку. Переделал с использованием стрелочной функции

2022-02-14 14:55 UTC, closed without merging