Complete the task
frontend-park-mail-ru/homework_2022_1 pull request #25
Opened 2022-02-09 09:57 UTC by senago

2022-02-10 06:26 UTC, Alkirys commented
Привет и добро пожаловать на 2 семестр Технопарка! Я буду проверять твое нулевое дз по фронтенду, так что в случае возникновения вопросов не стесняйся писать мне) Мой ник в телеге https://t.me/Alkirys.

2022-02-10 06:47 UTC, Alkirys requested changes

2022-02-10 06:47 UTC, Alkirys commented on source/solve.js
> +'use strict';
Круто, что ты знаешь про use strict. Но не мог бы ты рассказать, почему ты решил его использовать?)

2022-02-10 06:47 UTC, Alkirys commented on source/solve.js
> +function solve(expr, arg) {
А какие еще ты знаешь способы определить функцию в js?

2022-02-10 06:47 UTC, Alkirys commented on source/solve.js
> +var variableName = 'x';
в современной разработке предпочтительнее использовать ключевые слова let и const при создании переменных. Почитай про это и расскажи, в чем их преимущества

2022-02-10 06:47 UTC, Alkirys commented on source/solve.js
> + * @param {number} arg - The argument to the expression.
Отлично, что ты используешь JSDoc) но стоит также описывать и возвращаемое функцией значение. Подробнее можешь почитать [в доке](https://jsdoc.app/tags-returns.html)

2022-02-10 06:47 UTC, Alkirys commented on source/solve.js
> +    return eval(expr.replaceAll(variableName, arg.toString()));
Это действительно самый простой вариант решения задачи, но не кажется ли тебе, что он уж слишком прост?)
К тому же, функцию eval стараются не использовать, потому что она является небезопасной. Подумай, как можно еще решить эту задачку

2022-02-10 06:47 UTC, Alkirys commented on tests/solve.js
> +		assert.strictEqual(solve('42 + x', -12), 30);
Это хорошие кейсы для проверки, но подумай, какие еще случаи можно проверить

2022-02-10 08:05 UTC, senago commented on source/solve.js
> +'use strict';
Сначала писал на typescript, так что все им сгенерировано. Убрал его потом, потому что, наверное, это оверкилл и не хотел мучиться туда QUnit подключать. В целом, насколько я понимаю, strict уже всегда используется, потому что делает опасный js немного безопаснее и удобнее для дебага и работает почти в любом браузере.

2022-02-10 08:18 UTC, senago commented on source/solve.js
> +var variableName = 'x';
Да, странно, вроде это `tsc` выдал

`let`, кажется, во всем лучше `var`:
1. не поднимает (`hoisting`) переменные и, соответственно, реализует ясную и безопасную логику области видимости
2. запрещает redeclaration
3. запрещает создавать global state

здесь, конечно, `const variableName = 'x';` должно быть

2022-02-10 10:33 UTC, Alkirys commented on source/solve.js
> +'use strict';
Меня так и подмывает спросить, как можно сделать опасный js безопаснее?🙃

2022-02-10 10:35 UTC, Alkirys commented on source/solve.js
> +function solve(expr, arg) {
Отлично, а в чем различия у этих методов объявления?

2022-02-10 10:39 UTC, Alkirys commented on source/solve.js
> +var variableName = 'x';
👌

2022-02-13 10:17 UTC, senago commented on source/solve.js
> +'use strict';
Всех [деталей](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) не помню, но, в целом, добавляются небольшие статические проверки и в рантайме поведение становится более _строгим_ (вместо тихой ошибки бросится исключение)

2022-02-13 10:19 UTC, senago commented on source/solve.js
> +function solve(expr, arg) {
Если не ошибаюсь, только в первом случае сработает механизм поднятия символов вверх (hoisting)
То есть функции, определенные 2 и 3 способом, будут доступны только ниже их по коду

2022-02-13 10:22 UTC, senago commented on source/solve.js
> +    return eval(expr.replaceAll(variableName, arg.toString()));
Почитал про `eval`, этим лучше действительно не пользоваться. Потратил много времени и довольно хорошо разобрался с темой грамматик ([Context Free Grammar](https://en.wikipedia.org/wiki/Context-free_grammar)). Больше всего помогла [статья Норвелла](https://www.engr.mun.ca/~theo/Misc/exp_parsing.htm)

2022-02-13 16:57 UTC, Alkirys commented
Но на самом деле, в данной задаче работа с грамматиками - это оверкилл решение.  Почитай про [обратную польскую нотацию](https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F_%D0%BF%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C). Через нее можно проще решить задачу. А еще, ты реализовал функционал, который не требовался по условию задачи, так что перечитай еще раз тз.
Также, у меня есть несколько замечаний и вопросов по написанному коду.
Но в целом могу сказать,  что ты провел очень хорошую и обширную работу как по изучению грамматик, так и по изучению языка. Молодец! Я думаю, что ты уже вынес из дз0 больше знаний, чем большинство твоих однокурсников) Но совершенству нет предела🔥

2022-02-13 16:58 UTC, Alkirys requested changes

2022-02-14 11:39 UTC, senago commented on source/solve.js
> +          return expr;
Согласен, но оставлять грамматику неполной не хотелось)

2022-02-14 11:42 UTC, senago commented on source/solve.js
> +      }
Про работу c исключениями знаю, просто крайне не люблю их. Давно привык к идеальному для меня стилю, когда ошибка явно возвращается функцией. В Go можно особенно красиво писать, потому что возвращаемых значений из коробки много. В JS такой код будет не самым красивым (да еще и без типов...)

2022-02-14 12:10 UTC, senago commented on source/solve.js
> +    }
`===` дополнительно сравнивает типы выражений, то есть, по сути, исключает неявные преобразования

2022-02-14 12:37 UTC, senago commented on source/solve.js
> +    this.type = type
На описание всех классов мне не хватило сил :(
На мой взгляд, это немного лишнее, потому что сам процесс описания крайне простой (по технике), а сил может много затратить. При этом, конечно, код должен быть дескриптивным, чего я постарался достичь

2022-02-14 12:42 UTC, senago commented
Насчет обратной польской записи согласен. Но это уже давно пройденный этап, поэтому сейчас решил наконец-таки немного разобраться в грамматиках.

2022-02-14 14:07 UTC, Alkirys requested changes

2022-02-14 14:07 UTC, Alkirys commented on tests/solve.js
> +		assert.throws(() => solve('', 0));
и последний камень в огород тестов: во входные данные может попасть не только строка. 
Например, из-за каких-нибудь косяков в понимании описания апи бэка, в твою функцию может попасть объект или наоборот неопределенная переменная

2022-02-14 14:09 UTC, Alkirys commented on source/solve.js
> +
кстати о них, прокути выше, я там в одном из первых своих коментов задал еще один вопрос

2022-02-14 14:18 UTC, Alkirys commented
Понимаю, что энтузиазм в работе важен, но задачи нужно решать оптимально. Ты же не будешь строить космолет, чтобы перевезти 3 человек через Атлантический океан, потому что пароход - это уже пройденный этап. 
Так что, давай попробуем написать решение через обратную польскую нотацию. Тем более, если ты уже знаком с этим методом.
Я считаю, что в данном случае через это решение будет оптимальнее. Если ты не согласен, можем подискутировать на эту тему)

2022-02-14 15:23 UTC, senago commented on source/solve.js
> +  }
понимаю, просто люблю оборачивать в скобки (такой код кажется более красивым), особенно когда выражение довольно длинное

2022-02-14 15:31 UTC, senago commented on source/solve.js
> +   * Create a token.
Согласен. С написанием документации уже сталкивался (в основном апи), поэтому понимаю, насколько это может быть полезным. Сейчас просто совсем не хочется тратить время на их написание :(

2022-02-14 17:33 UTC, senago commented
Добавил решение с RPN, но с ним есть проблемы - тесты на выражениях с несколькими унарными операторами падают. Думаю, это можно легко поправить (проблема и в генерации RPN, и в её исполнении), но быстро сделать это не получилось, и времени поджимает, к сожалению :(

2022-02-14 23:18 UTC, Alkirys requested changes

2022-02-14 23:18 UTC, Alkirys commented on source/solve.js
> +        ch = this.peekChar();
у тебя тут 2 if-а, в которых по 8 строк, хотя различается в них только одна строка

2022-02-14 23:18 UTC, Alkirys commented on source/solve.js
> +  const stack = [];
опять логирование в консоль(

2022-02-14 23:18 UTC, Alkirys commented on source/solve.js
> +        }
а почему тут ==

2022-02-14 23:18 UTC, Alkirys commented on source/solve.js
> +        }
если stack.length == 1 это костыль, чтобы унарный минус работал, то во-первых, костыли - это плохо, а во-вторых, он не всегда работает. Попробуй прогнать (x + 1) * -1

2022-02-15 11:34 UTC, senago commented on source/solve.js
> +        ch = this.peekChar();
Поправил, добавил scanNumberPiece, чтобы не было повторений

2022-02-16 10:50 UTC, Alkirys commented
Отлично)
Пересмотрел твой код. Давай все-таки еще поработаем над документацией для классов. Пример можешь найти [здесь](https://jsdoc.app/howto-es2015-classes.html)

2022-02-16 13:09 UTC, Alkirys approved these changes

2022-02-16 16:08 UTC, closed without merging