Мужецкий Антон 19 вариант
frontend-park-mail-ru/homework_2022_1 pull request #27
Opened 2022-02-09 10:11 UTC by muzhts-anton

2022-02-09 19:54 UTC, Shureks-den commented
Привет! Добро пожаловать на курс фронтенда. Желаю тебе удачи и надеюсь, что после этого курса в тебе проснется внутренний фронтендер :) Если будут вопросы или нужно будет проверить правки можешь писать мне в телегу https://t.me/alexklonov

2022-02-09 20:28 UTC, Shureks-den requested changes

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +const sorting = (arr, keys) => {
Круто, что используешь стрелочные функции, вопрос по ним: какие способы задания функций ты вообще знаешь, и в чем особенность стрелочных функций

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +    if (!Array.isArray(arr) || !Array.isArray(keys) || arr.length == 0 || keys.length == 0) {
Кажется, что лучше в случае некорректного формата лучше возвращать undefined или бросать ошибку, а в случае нулевой длины возвращать исходные массивы

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +    const tmp = Object.assign([], [...arr]);
Вижу, что ты копируешь исходный массив. Тогда сначала вопрос на понимание - для чего ты это делаешь? А потом технический вопрос - насколько я понял у тебя в задании написано сортировку **этого** массива, значит нужно менять именно исходный массив

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +    const tmp = Object.assign([], [...arr]);
Второй 'классический' вопрос. Расскажи чем отличаются var, const, let, что в каких случаях стоит использовать, а в каких не стоит :)

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +    keys.reverse().forEach(it => {
Не до конца понимаю, зачем реверсить массив ключей. Можешь написать причину?

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +            if (typeof last[it] == 'number' || typeof next[it] == 'number') {
Какими еще способами можно проверить, что данный объект число?

2022-02-09 20:28 UTC, Shureks-den commented on source/sorting.js
> +                if (last[it] > next[it]) {
Имхо, но думаю, что else if красивее

2022-02-10 10:59 UTC, muzhts-anton commented on source/sorting.js
> +'use strict';
Чтобы активировать новые возможности в языке, ибо с определенного обновления джс изменил некоторые возможности старой версии и перестал их поддерживать.

2022-02-10 11:03 UTC, muzhts-anton commented on source/sorting.js
> +const sorting = (arr, keys) => {
Есть возможность передать функцию в качестве обычного аргумента, можно использовать Function Expression. Стрелочные функции - это синтаксически упрощенный вариант Function Expression.

2022-02-10 11:18 UTC, muzhts-anton commented on source/sorting.js
> +    const tmp = Object.assign([], [...arr]);
1) Действительно, безобразие.
2) var - игнорирует блочные области видимости(жизни) переменной. Дает возможность использовать переменную вне блока ее объявления. Ее область видимости ограничивается скриптом или функцией. Допускает повторное объявление. В последнее время считается устаревшим способом объявления переменной.
let - объявление переменной с привычными правилами области видимости.
const - объявление неизменяемой переменной.

2022-02-10 11:25 UTC, muzhts-anton commented on source/sorting.js
> +    keys.reverse().forEach(it => {
ключи ("фильтры" сортировки) передаются в порядке важности. т.е., например, в случае двух ключей, по первому из них необходима строгость, второй же будет решать порядок элементов, считающихся эквивалентными по первому ключу. (логика та же, как, например, 19 меньше 24, ибо сначала смотрим на 1<2, а не на 9<4). Функция же, передаваемая в foreach, обеспечивает стабильную сортировку. Соответственно, если сортировать не в реверсивном порядке, то по главенствующему параметру сортировка будет проходить первой. Сл-но, при повторном пробеге по массиву с новым ключом, порядок будет нарушен в угоду новому ключу)

2022-02-10 11:29 UTC, muzhts-anton commented on source/sorting.js
> +            if (typeof last[it] == 'number' || typeof next[it] == 'number') {
например, через Number.isInteger()

2022-02-10 12:37 UTC, Shureks-den approved these changes

2022-02-10 12:37 UTC, Shureks-den commented on source/sorting.js
> +    keys.reverse().forEach(it => {
Ага понял, спасибо

2022-02-10 12:41 UTC, Shureks-den commented on source/sorting.js
> +'use strict';
Можешь подробнее расписать? И влияет ли он на безопасность кода?

2022-02-10 13:25 UTC, muzhts-anton commented on source/sorting.js
> +'use strict';
Во-первых, строгий режим заменяет исключениями некоторые ошибки, которые интерпретатор JavaScript ранее молча пропускал. Во-вторых, строгий режим исправляет ошибки, которые мешали движкам JavaScript выполнять оптимизацию -- в некоторых случаях код в строгом режиме может быть оптимизирован для более быстрого выполнения, чем код в обычном режиме. В-третьих, строгий режим запрещает использовать некоторые элементы синтаксиса.
Строгий режим делает невозможным случайное создание глобальных переменных. В обычном JavaScript опечатка в имени переменной во время присваивания приводит к созданию нового свойства глобального объекта, и выполнение продолжается (хотя в современном JavaScript оно, вероятно, аварийно завершится в дальнейшем). Присваивания, которые могут случайно создать глобальную переменную, в строгом режиме выбрасывают исключение. 
Строгий режим заставляет присваивания, которые всё равно завершились бы неудачей, выбрасывать исключения. 
В строгом режиме попытки удалить неудаляемые свойства будут вызывать исключения. 
Строгий режим требует, чтобы все свойства, перечисленные в сериализованном объекте, встречались только один раз. 
Строгий режим требует, чтобы имена аргументов в объявлении функций встречались только один раз. 
Строгий режим запрещает синтаксис восьмеричной системы счисления.
Конечно, есть и другие изменения и особенности.

2022-02-14 13:28 UTC, Betchika99 requested changes
привет) добро пожаловать на курс)

ты неплохо решил задачу, но есть несколько замечаний и вопросов по твоему коду.

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-14 13:28 UTC, Betchika99 commented on source/sorting.js
> +    keys.reverse().forEach(it => {
для лучшей читаемости все параметры функций оборачивают в круглые скобки ()

2022-02-14 13:28 UTC, Betchika99 commented on source/sorting.js
> +            if (typeof last[it] == 'number' || typeof next[it] == 'number') {
расскажи, почему нельзя обойтись без этого if и сразу сравнивать через intl?

2022-02-14 13:28 UTC, Betchika99 commented on source/sorting.js
> +                let collator = new Intl.Collator(undefined, {
почему ты используешь здесь let?

2022-02-14 13:28 UTC, Betchika99 commented on source/sorting.js
> +                let collator = new Intl.Collator(undefined, {
почему ты передаешь в Itl.Collator undefined явно?

2022-02-14 13:28 UTC, Betchika99 commented on source/sorting.js
> +        arr.sort((last, next) => { // sort stability is observed
чем плох стандартный метод сортировки для массивов?

2022-02-14 13:28 UTC, Betchika99 commented on source/sorting.js
> +    return arr;
не очень нравится, что ты изменяешь исходный переданный массив. функции нужно стараться делать чистыми, чтобы они внутри себя не изменяли входные данные

2022-02-14 14:35 UTC, muzhts-anton commented on source/sorting.js
> +            if (typeof last[it] == 'number' || typeof next[it] == 'number') {
Насколько мне известно, intl умеет сравнивать строки, но не числа. Числа он умеет только форматировать. Поэтому, для нормальной работы с числами, необходимо рассмотреть этот случай отдельно.

2022-02-14 14:38 UTC, muzhts-anton commented on source/sorting.js
> +                let collator = new Intl.Collator(undefined, {
эта переменная мне не нужна вне этого блока, поэтому устаревшее var явно не нужно. что касается const - можно использовать и его, так как переменную я действительно не изменяю. Исправил.

2022-02-14 14:44 UTC, muzhts-anton commented on source/sorting.js
> +                let collator = new Intl.Collator(undefined, {
первым аргументом передается локаль (locales). я решил не уточнять локаль, хотя мог бы указать массив из ожидаемых языков. в задании об этом ничего не говорилось

2022-02-14 14:58 UTC, closed without merging