i did it
frontend-park-mail-ru/homework_2022_1 pull request #28
Opened 2022-02-09 10:24 UTC by shevvvo

2022-02-10 11:04 UTC, DPeshkoff requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

2022-02-11 11:25 UTC, DPeshkoff requested changes
Привет)
Еще нужно кое-что поправить

2022-02-11 11:25 UTC, DPeshkoff commented on source/set.js
> +    }*/
Закомментированного кода быть не должно)

2022-02-11 11:25 UTC, DPeshkoff commented on source/set.js
> +    }
Эта проверка не сработает в случае, например, `Object.create(null);`

Для проверки на объект лучше воспользоваться `typeof`. Не стоит забывать про [ошибку](https://learn.javascript.ru/types#type-typeof)

2022-02-11 11:25 UTC, DPeshkoff commented on source/set.js
> +            list[key] = {}
Не забывай про `;`

2022-02-11 11:25 UTC, DPeshkoff commented on source/set.js
> +    let last = newPath.at(-1);
А зачем эта переменная? Кажется, если ее встроить в 39, то она не станет от этого менее читабельной

2022-02-11 19:22 UTC, shevvvo commented on source/set.js
> +'use strict';
В js автоматически включена поддержка устаревшего кода. use strict отключает это и код исполняется в современном режиме.

2022-02-11 19:50 UTC, DPeshkoff requested changes
Привет!
Финишная прямая, минорные правки)

2022-02-11 19:50 UTC, DPeshkoff commented on source/set.js
> +        throw new Error('It s not an object');
Давай сделаем более понятное сообщение об ошибке - а то не очень очевидно, что за it и почему оно is not an object

2022-02-11 19:50 UTC, DPeshkoff commented on source/set.js
> +        throw new Error('bad path');
Еще можно тут и на строке 12 `TypeError` - так будет логичнее)

2022-02-11 19:50 UTC, DPeshkoff commented on tests/set.js
>  });
Можно еще добавить тест на создание новых свойств

2022-02-11 20:21 UTC, DPeshkoff approved these changes

2022-02-15 13:41 UTC, Betchika99 commented on source/set.js
> + * @param {String} path - path to the property
Object и String - это конструкторы, а не типы :) с маленькой буквы будет правильнее написать

2022-02-15 13:43 UTC, Betchika99 commented on source/set.js
> +    if (typeof(obj) !== 'object') {
1) после typeof не нужны круглые скобки (здесь и дальше)
2) `typeof null === 'object'`, так что проверка не корректная =(

2022-02-15 13:44 UTC, Betchika99 commented on source/set.js
> +    const newPath = path.split('.');
давай здесь сразу отфильтруем элементы, которые равно пустой строке (как минимум, первый)

2022-02-15 13:45 UTC, Betchika99 commented on source/set.js
> +    if (!(path instanceof String) && typeof(path) !== 'string') {
а если в path нету ни одной точки? или это пустая строка вообще? тоже невалидные кейсы

2022-02-15 13:47 UTC, Betchika99 commented on source/set.js
> +            list[key] = list[key];
в чем смысл этой строчки?)

2022-02-15 13:47 UTC, Betchika99 commented on source/set.js
> +        }
давай добавим пустую строку здесь, чтобы отделить визуально блоки

2022-02-15 13:50 UTC, Betchika99 commented on source/set.js
> +    newObj[newPath.at(-1)] = value;
если `at` не найдет элементов, то здесь будет ошибка обращения к свойству объекта =(

2022-02-15 13:56 UTC, Betchika99 commented on tests/set.js
> +	});
давай добавим здесь кейсов, когда второй аргумент явно плохой - null, пустая строка, строка без точек и т.п.

2022-02-16 11:33 UTC, closed without merging