Тадевосян Эрик 9 вариант
frontend-park-mail-ru/homework_2022_1 pull request #29
Opened 2022-02-09 13:51 UTC by erik770

2022-02-09 20:38 UTC, fillinmar reviewed
Поздравляю тебя с переходом на 2 семестр и приветствую на курсе фронтенда! Оставила пару комментариев по твоему решению. Если будут вопросы, то можешь писать в комменты или в [телеграм](https://telegram.me/fillinmar)

2022-02-09 20:38 UTC, fillinmar commented on source/anagram.js
> +function sortLettersInWord(word) {
Желательно использовать стрелочные функции

2022-02-09 20:38 UTC, fillinmar commented on tests/anagram.js
> +			'аз есмь строка живу я мерой остр.', 'ракета',
Советую разделить тесты (например, тест на предложения, тест на русские слова, тест на англ слова)

2022-02-09 20:43 UTC, fillinmar commented
также не забудь еще про [jsdoc] (https://jsdoc.app/)

2022-02-09 21:02 UTC, fillinmar commented
не забудь сделать проверку входных данных

2022-02-10 09:39 UTC, fillinmar commented on source/anagram.js
> +    if (!isValidInput(words)) {
ты эту функцию используешь до ее объявления, лучше бы сделать наоборот

2022-02-10 09:41 UTC, fillinmar commented on source/anagram.js
> + * @param {object} words
твоя функция принимает массив строк, а не просто объект, в jsdoc лучше указать на это

2022-02-10 09:45 UTC, fillinmar commented on source/anagram.js
> +        return null;
если введенные данные не верные, то лучше генерировать [исключения](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw)

2022-02-10 09:46 UTC, fillinmar commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно со словосочетаниями и предложениями', function (assert) {
сделай пожалуйста еще тесты, где в массиве нет анаграмм

2022-02-10 13:48 UTC, fillinmar reviewed
оч круто, осталось совсем чуть-чуть

2022-02-10 13:48 UTC, fillinmar commented on source/anagram.js
> +const isValidInput = (words) => {
параметр @function излишен, у тебя ниже написано название функции

2022-02-10 13:48 UTC, fillinmar commented on source/anagram.js
> + * @param {string[]} words
поясни что за входной параметр

2022-02-14 13:08 UTC, Betchika99 requested changes
привет) добро пожаловать на курс)

мне очень понравилось твое решение, все в духе современного JS, лайк!  но есть несколько небольших замечаний.

особое внимание прошу уделить: проверь свое решение (в тч тесты) на предмет [код-стайла](https://learn.javascript.ru/coding-style). Где-то не хватает отступов между блоками, где-то точки с запятой, где-то кавычки отличаются. Все должно быть красиво

а еще расскажи коротко - как можно было бы сделать твой алгоритм без Map? чтобы ты использовал и как бы действовал? кодить не надо, только рассказать)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-14 22:03 UTC, erik770 commented on source/anagram.js
> + * @param {*} words - input data which requires validation for correct future usage
тут не совсем согласен но все же поправлю. у нас ведь суть функции в том чтобы проверить правильность входных данных и как раз таки тут мы ожидаем что угодно.. а массив строк лишь в хорошем, подходящем дня нас случае

2022-02-14 22:32 UTC, erik770 commented on source/anagram.js
> +    let map = new Map();
для создания переменной мы используем ключевое слово let. в данном случае мы можем и нужно скорее использовать ключевое слово const которое создает константную(неизменяемую) переменную. это нужно для того чтобы код был безопаснее(попытка изменить переменную приведет к ошибке) и чтобы наглядно показать что данная переменная не будет изменяться в дальнейшем

2022-02-14 22:32 UTC, erik770 commented on source/anagram.js
> +        map.get(wordToKey(word)).push(word);
да, стоило бы

2022-02-14 22:38 UTC, erik770 commented
алгоритм без Map я сделал в первой версии своего кода, там я создал еще один массив строк состоящий из отсортированных букв входящих в слова. после я вложенно итерировался по нему и если видел что "коды" слов совпадают то добавлял их по индексу(индексы в обоих массивах были одни и те же). вооот... а плох этот способ тем что очевидно там у меня вложенный цикл и алгоритм поиска получается сложнее. тут же мы все делаем за один проход

2022-02-14 22:41 UTC, erik770 commented on source/anagram.js
> +    })
заменил

2022-02-15 15:52 UTC, closed without merging