Калашков Павел Вариант 9
frontend-park-mail-ru/homework_2022_1 pull request #3
Opened 2022-02-05 15:52 UTC by kalashkovpaul

2022-02-09 15:06 UTC, dnlipko commented on source/anagram.js
> +        result.sort((a, b) => a[0] > b[0]);
Функция сортировки в таком виде не работает, в [доке](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description) можно найти описание функции сравнения

2022-02-09 15:06 UTC, dnlipko commented on source/anagram.js
> +function anagram(array) {
Немного поправим алгоритм решение. Сейчас для каждого слова в массиве осуществляется проход по массиву result в поисках подходящей группы анаграмм. Эту часть можно упростить воспользовавшись объектом с поиском ключу.

2022-02-09 15:07 UTC, dnlipko commented on source/anagram.js
> +    for (let i = 0; i < array.length; i++) {
В js несколько хороших [способов итерации](https://learn.javascript.ru/array-iteration) по массиву(объекту), которые делают код более читаемым и понятным) давай воспользуемся ими

2022-02-09 15:07 UTC, dnlipko commented on source/anagram.js
> +            let secondWord = String(array[j]);
имхо проще использовать [шаблонные строки](https://learn.javascript.ru/es-string)

2022-02-09 15:10 UTC, dnlipko commented on source/anagram.js
> +function alreadyProcessed(word, matrix)
Чаще всего для создания функции используют [стрелочные функции](https://learn.javascript.ru/arrow-functions-basics)

2022-02-09 15:14 UTC, dnlipko commented on source/anagram.js
> +            if (firstSorted === secondSorted)
Считаю хорошим тоном использовать фигурные скобки даже если в ифе одно выражение. Либо записывать их в одну строку. Стайл [гайд](https://learn.javascript.ru/coding-style) по js в помощь.

2022-02-11 08:20 UTC, dnlipko commented on source/anagram.js
> +    function process(word)
Проверь свой код на соответствие [стайл-гайду](https://learn.javascript.ru/coding-style)

2022-02-11 08:21 UTC, dnlipko commented on source/anagram.js
> +    function process(word)
Давай использовать стрелочные функции 
https://learn.javascript.ru/arrow-functions-basics

2022-02-11 08:22 UTC, dnlipko commented on source/anagram.js
> +        let wordSorted = sortWord(word);
Лучше использовать const если переменная дальше не изменяется

2022-02-11 08:25 UTC, dnlipko commented on source/anagram.js
> +    array.forEach(process);
Не самая лучшая идея здесь использовать forEach. Здесь ты проходишься по массива и накапливаешь ново значение в result. Для этого хорошо подойдет `reduce` https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2022-02-11 08:26 UTC, dnlipko commented on source/anagram.js
> +        result = Object.values(result);
Можно использовать [чейнинг](https://learn.javascript.ru/task/chain-calls)
`Object.values().filter().map()`

2022-02-11 08:27 UTC, dnlipko commented on source/anagram.js
> +        result = result.filter((array) => array.length >= 2)
`> 1` ?

2022-02-11 08:31 UTC, dnlipko commented on source/anagram.js
> +    result = result.length === 0 ? null :
Чтобы выражение не было таким длинным давай разделим его на две части 

```
if (result.length === 0) {
    return null;
}

return result.sort((a, b) => a[0] > b[0] ? 1 : a[0] < b[0] ? -1 : 0);



```

2022-02-11 08:44 UTC, dnlipko commented on source/anagram.js
> +    function process(word)
process будет пересоздаваться каждый раз при вызове anagram. Давай вынесем process в отдельный метод

2022-02-11 08:49 UTC, dnlipko commented on source/anagram.js
> +function anagram(array) {
const anagram = () => {}

2022-02-13 20:32 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

ты неплохо решил задач, но есть несколько комментов, обрати на них внимание. Также предлагаю тебе посмотреть в сторону более современных механизмов в языке, таких как [set и map](https://learn.javascript.ru/map-set) и заиспользовать их в своем коде :)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-13 20:32 UTC, Betchika99 commented on source/anagram.js
> + * @param {string} word Слово, буквы которого будем сортировать
нет описания @return в jsdoc

2022-02-13 20:32 UTC, Betchika99 commented on source/anagram.js
> +  if (cur_result.hasOwnProperty(wordSorted)) {
в js принят camelCase

2022-02-13 20:32 UTC, Betchika99 commented on source/anagram.js
> + * @param {array} wordList Массив слов, который будет разбиваться на группы-анаграммы
[посмотри](https://jsdoc.app/tags-param.html) внимательнее, как объявляются массивы в jsdoc

2022-02-13 20:32 UTC, Betchika99 commented on source/anagram.js
> +const process = (cur_result, word) => {
давай назовем функцию как-то более информативно

2022-02-13 20:32 UTC, Betchika99 commented on source/anagram.js
> +  return cur_result
здесь пропущена точка с запятой. Посмотри внимательнее всё свое дз (в т.ч. тесты) на правильность [код-стайла](https://learn.javascript.ru/coding-style)

2022-02-13 20:32 UTC, Betchika99 commented on source/anagram.js
> +const anagram = (wordList) => {
а где проверка корректности входных данных? если тебе сюда передали какие-то числа или вообще ничего? Давай добавим проверку и напишем на это тесты

2022-02-14 05:01 UTC, kalashkovpaul commented on source/anagram.js
> +const anagram = (wordList) => {
Готово)
Все поправки сделал, всё по факту) set начал использовать, негативные проверки на входные данные добавил

2022-02-14 14:37 UTC, Betchika99 requested changes
крайний рывок (я надеюсь)! как поправишь, напиши плз в тг

2022-02-14 14:37 UTC, Betchika99 commented on source/anagram.js
> +    let anagramGroup = curResult.get(wordSorted);
почему здесь используешь `let`? переменная же не меняется

2022-02-14 14:37 UTC, Betchika99 commented on source/anagram.js
> +  if (!Array.isArray(wordList) || wordList.length == 0 || typeof(wordList[0]) != "string")
1) после typeof не нужны круглые скобки
2) кавычки во всем доке одинарные, не надо нам других
3) не хватает фигурных скобок для красоты + пустой строки после этого if
4) не забывай про точки с запятой, а то где-то грустит один котик

2022-02-14 14:37 UTC, Betchika99 commented on source/anagram.js
> +  anagramGroup = Array.from(anagramGroup.values()).filter((wordList) => wordList.length > 1).map(wordList => wordList.sort());
это можно в одну строчку сделать и тогда переменная не будет переиспользуемой (будет const). Только раздели каждый метод на новую строчку, чтобы это было более читаемо

2022-02-15 15:45 UTC, closed without merging