Do variant 12
frontend-park-mail-ru/homework_2022_1 pull request #31
Opened 2022-02-09 14:26 UTC by kdv2001

2022-02-10 02:34 UTC, DPeshkoff requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

2022-02-10 02:34 UTC, DPeshkoff commented on source/minmax.js
> +'use strict';
Можешь, пожалуйста, рассказать, зачем это нужно?

2022-02-10 02:34 UTC, DPeshkoff commented on source/minmax.js
> +    }
А что будет, если твой код будет использовать неопытный программист, который подаст тебе на вход, например, массив?
Было бы неплохо подстраховаться и проверять аргументы)

2022-02-10 02:34 UTC, DPeshkoff commented on source/minmax.js
> +        }
А здесь можно применить [reduce](https://learn.javascript.ru/array-methods#reduce-reduceright) и это сделает код более понятным и красивым)

2022-02-10 02:34 UTC, DPeshkoff commented on source/minmax.js
> +const minmax = (value) => {
Очень круто, что пишешь стрелочные функции!
Расскажи, пожалуйста, чем они отличаются от обычных `function`?

2022-02-10 02:34 UTC, DPeshkoff commented on tests/minmax.js
> +
Тесты - это круто)
Давай напишем еще тест на некорректные входные данные)

2022-02-10 20:48 UTC, kdv2001 commented on source/minmax.js
> +'use strict';
это нужно чтобы код обрабатывался в строгом(современном) режиме

2022-02-10 21:23 UTC, kdv2001 commented on source/minmax.js
> +const minmax = (value) => {
они отличаются тем, что у них нет this

2022-02-11 11:53 UTC, DPeshkoff requested changes
Привет)
Нужно еще кое-что поправить:

2022-02-11 11:53 UTC, DPeshkoff commented on tests/minmax.js
> +
А если будет объект?)

2022-02-11 11:53 UTC, DPeshkoff commented on source/minmax.js
> +        if (!max || numberCurrent === Infinity || max < numberCurrent) {
Бесконечности можно передать как значения по умолчанию - тогда код будет легче читать)

2022-02-11 17:57 UTC, DPeshkoff requested changes
Привет!
Осталось еще немного)

2022-02-11 17:57 UTC, DPeshkoff commented on source/minmax.js
> +    if (typeof (value) != 'string') {
Здесь нужно [строгое сравнение](https://learn.javascript.ru/comparison#strogoe-sravnenie) 

Кроме того, строки могут и не иметь `typeof === 'string'`, к примеру:

`typeof(new String('string'))` вернет `'object'`)

Я бы добавил проверку и на это. [Здесь](https://learn.javascript.ru/instanceof) можно почитать, как это сделать)

2022-02-11 17:57 UTC, DPeshkoff commented on source/minmax.js
> +        return [undefined, undefined];;
Лишняя `;`

2022-02-11 17:57 UTC, DPeshkoff commented on source/minmax.js
> +        return [undefined, undefined];;
Лишняя `;`

2022-02-11 17:57 UTC, DPeshkoff commented on source/minmax.js
> +    politeValue = politeValue.map(string => parseFloat(string));
Строчки 18 и 17 можно объединить - в JS можно делать [цепи вызовов ](https://learn.javascript.ru/task/chain-calls)

Кроме того, не поправил двойную конвертацию(
Обрати внимание на порядок методов и исправь это)

Вместо isNaN лучше использовать [кое-что другое](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) :)

И эта переменная вполне себе может быть `const`)
У констант в JS вообще очень интересные свойства, советую [ознакомиться](https://learn.javascript.ru/let-const#const)

2022-02-11 17:57 UTC, DPeshkoff commented on source/minmax.js
> +    return politeValue.reduce(([min, max], current) => {
Ты просто убрал бесконечности, а я написал, что их лучше передавать как [параметры по умолчанию](https://learn.javascript.ru/function-basics#parametry-po-umolchaniyu) (у функций-стрелок то же самое)

2022-02-11 17:57 UTC, DPeshkoff commented on source/minmax.js
> +        }
Если добавить значения по умолчанию, то `!min` и `!max` будут не нужны)

2022-02-11 20:02 UTC, DPeshkoff requested changes
Привет)
Осталось немного)

2022-02-11 20:02 UTC, DPeshkoff commented on source/minmax.js
> +        return [min, max];
А это можно переписать с использованием [условного оператора](https://learn.javascript.ru/ifelse#uslovnyy-operator) и объединить с return, станет еще красивее)

2022-02-11 20:57 UTC, DPeshkoff requested changes

2022-02-11 20:57 UTC, DPeshkoff commented on source/minmax.js
> +    const splitValue = value.split(' ').map(string => parseFloat(string)).filter((item) => !Number.isNaN(item));
У тебя есть очень длинные строки (12, 9, 14, 15), которые затрудняют чтение кода(
Оптимальная длина строки - 80 символов
Давай сделаем переносы так, чтобы все строки были короче 80 символов?

2022-02-12 11:32 UTC, DPeshkoff approved these changes

2022-02-15 15:37 UTC, Betchika99 requested changes
привет) рада видеть тебя на нашем курсе.

неплохое решение, молодец) есть несколько небольших замечаний, обрати на них внимание.

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-15 15:37 UTC, Betchika99 commented on source/minmax.js
> +  if (!(typeof (value) === 'string' || value instanceof String) || (value === '')) {
1) после typeof не нужны круглые скобки
2) давай вместо проверки на пустую строку сделаем проверку `!value`, чтобы покрыть больше невалидных кейсов

2022-02-15 15:37 UTC, Betchika99 commented on source/minmax.js
> +};
не очень читаемый блок, давай вынесем функцию внутри `reduce` извне (в отдельный блок) и добавим дополнительных переносов строк

2022-02-15 19:43 UTC, closed without merging