Частиков Александр WEB-11
frontend-park-mail-ru/homework_2022_1 pull request #32
Opened 2022-02-09 16:41 UTC by papazloynt

2022-02-10 03:05 UTC, DPeshkoff requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

Кроме того, приведи, пожалуйста, pull request в соответствии с правилами (`Фамилия Имя №_Варианта`) и исправь PR, чтобы он мерджился в ветку варианта

2022-02-10 03:05 UTC, DPeshkoff commented on tests/get.js
> +});
В [ветке варианта репозитория с домашним заданием](https://github.com/frontend-park-mail-ru/homework_2022_1/blob/variant-13/tests/get.js) было больше тестов, не нужно их удалять)

Давай допишем еще тесты на некорректные входные данные

2022-02-11 14:37 UTC, papazloynt commented on source/get.js
> +"use strict";
Использую эту строчку, т.к. фишками старого стандарта мне пользоваться нет необходимости, я пишу современный код

2022-02-11 18:27 UTC, DPeshkoff requested changes
Привет!
Нужно кое-что еще поправить:

2022-02-11 18:27 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Исходный пример можно было оставить, но ладно, это не особо критично)

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> + * @param {any} object - return a property of this object
По условию нужен object, а он не any =)

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> + * @returns {any | undefined} - if path is correct than return value of property else return undefined
Вместо any можно *

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> +    if (!object || typeof (path) !== 'string') { return undefined }
Лучше блок вынести на новую строку и добавить ;

Кроме того, можно [упростить return](https://learn.javascript.ru/function-basics#vozvrat-znacheniya)

А еще строки могут и не иметь `typeof === 'string'`, к примеру:

`typeof(new String('string'))` вернет `'object'`)

Я бы добавил проверку и на это. [Здесь](https://learn.javascript.ru/instanceof) можно почитать, как это сделать)

Ну и еще - было бы круто проверять, что `object` на самом деле является объектом)

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> +        }
Можно без return - forEach [почти невозможно остановить](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#description))

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> +            obj = obj[propertyValue];
Здесь можно проверять [короче](https://developer.mozilla.org/ru/docs/Glossary/Truthy)

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> +    let keys = path.split('.');
Ключи могут без зазрений совести стать `const`)

2022-02-11 18:27 UTC, DPeshkoff commented on source/get.js
> +    // задано в таком виде: ["first_word second_word"])
Такое можно вынести в jsdoc - так будет заметнее, потому что многие IDE показывают документацию по наведению)
<img width="894" alt="Снимок экрана 2022-02-11 в 21 24 12" src="https://user-images.githubusercontent.com/31134795/153648312-a1ff1474-e713-4879-89a6-61fcbf02db72.png">
)

2022-02-11 18:27 UTC, DPeshkoff commented on tests/get.js
> -		};
А зачем тут убирать исходные тесты?

2022-02-11 18:27 UTC, DPeshkoff commented on tests/get.js
> +});
Нет перевода на новую строку в конце строки ([почему это важно](https://semakin.dev/2020/05/no_newline_at_end_of_file/))

2022-02-11 19:22 UTC, papazloynt commented on tests/get.js
> -		};
Я решил разюить на два модуля, которые как мне кажется проще воспринимать

2022-02-11 20:09 UTC, DPeshkoff requested changes

2022-02-11 20:09 UTC, DPeshkoff commented on tests/get.js
> -		};
Лучше верни - так будет проще, потому что второго модуля сейчас в репозитории я не вижу)

2022-02-14 20:12 UTC, DPeshkoff approved these changes

2022-02-15 17:03 UTC, Betchika99 requested changes
привет) рада видеть тебя на нашем курсе.

ты неплохо решил задачу, но есть некоторые небольшие ошибки/замечания. 

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya). Как все поправишь, лучше тоже напиши в тг.

2022-02-17 13:11 UTC, closed without merging