Хайруллин Ринат Вариант 12
frontend-park-mail-ru/homework_2022_1 pull request #34
Opened 2022-02-14 12:37 UTC by rinatkh

2022-02-14 18:45 UTC, senago requested changes

2022-02-14 18:45 UTC, senago commented on source/minmax.js
> +}
Нужна пустая линия в конце

2022-02-14 18:45 UTC, senago commented on source/minmax.js
> +const minmax = (strNumbers) => {
Добавь комментарии в стиле [JSDoc](https://jsdoc.app/index.html)

2022-02-14 18:45 UTC, senago commented on source/minmax.js
> +    return [min, max]
Лучше все-таки использовать `;`
Например, [тут](https://betterprogramming.pub/the-use-of-the-javascript-semicolon-843fd5e94d0e) написано, почему

2022-02-14 18:45 UTC, senago commented on source/minmax.js
> +    strNumbers = strNumbers.replace(/[а-я\,\+]/gi, '')
Думаю, лучше пояснить комментарием, что именно регулярка захватывает

2022-02-15 09:47 UTC, Alkirys requested changes

2022-02-15 09:47 UTC, Alkirys commented on source/minmax.js
> +    let max = Math.max(...numbers);
расскажи побольше про spread оператор

2022-02-15 09:47 UTC, Alkirys commented on tests/minmax.js
> +    });
подумай, какие еще кейсы могут быть при проверке 'minmax без чисел'

2022-02-15 09:47 UTC, Alkirys commented on source/minmax.js
> +        return [undefined, undefined];
в js есть оператор ===. Почитай и расскажи о различиях между == и === и подумай, что здесь лучше использовать

2022-02-15 09:47 UTC, Alkirys commented on source/minmax.js
> +    let max = Math.max(...numbers);
здесь лучше объявлять переменные как константы, они же не изменяются потом)

2022-02-15 09:47 UTC, Alkirys commented on source/minmax.js
> +    strNumbers = strNumbers.replace(/[а-я\,\+]/gi, '');
ммм... а если в строке будут английские символы? 
здесь лучше воспользоваться поиском с инверсией

2022-02-15 09:48 UTC, Alkirys commented
Привет и добро пожаловать на 2 семестр Технопарка! Как-то так вышло, что тебя уже немного поревьюили🧐, но я докину еще несколько замечаний) В случае возникновения вопросов не стесняйся писать [мне](https://t.me/Alkirys.) в телегу)

У меня есть несколько комментариев, но в целом могу сказать, что ты отлично поработал. Отдельный респект за использование стрелочных функций👍

2022-02-15 09:49 UTC, Alkirys commented
Вижу, что ты добавил .gitignore, но что-то явно пошло не так) убери из репы ненужные xml

2022-02-15 10:44 UTC, Alkirys commented on source/minmax.js
> +    strNumbers = strNumbers.replace(/[а-я\,\+]/gi, '');
а еще до меня тут дошло, что задачу можно решить гораздо проще и оптимальнее. 
js хорошо умеет кастить типы и в частности, создавать одни типы на основе других. Подумай об этом

2022-02-16 10:52 UTC, Alkirys commented
И еще одно замечание. Называй коммиты более осознанно. Когда будешь работать над проектом, это поможет тебе не запутаться

2022-02-16 21:19 UTC, rinatkh commented on source/minmax.js
> +'use strict';
нужен для того, чтобы код обрабатывался в современном режиме

2022-02-16 21:22 UTC, rinatkh commented on source/minmax.js
> +    strNumbers = strNumbers.replace(/[а-я\,\+]/gi, '');
преимущество в том, что у стрелочных нет собственных this и arguments

2022-02-16 21:25 UTC, rinatkh commented on source/minmax.js
> +        return [undefined, undefined];
Оператор == сравнивает на равенство, а вот === на идентичность. Плюс оператора === состоит в том, что он не приводит два значения к одному типу. Да, в данном случае лучше ===

2022-02-16 21:28 UTC, rinatkh commented on source/minmax.js
> +    let max = Math.max(...numbers);
Оператор spread позволяет расширять выражения в тех местах, где предусмотрено использование нескольких аргументов.

2022-02-17 07:39 UTC, Alkirys commented on source/minmax.js
> +'use strict';
а поподробнее, какие есть преимущества у этого режима?

2022-02-17 07:44 UTC, Alkirys commented on source/minmax.js
> +    strNumbers = strNumbers.replace(/[а-я\,\+]/gi, '');
получается, это функция без this и arguments? а как тогда это работает?

2022-02-17 07:47 UTC, Alkirys commented on source/minmax.js
> +    let max = Math.max(...numbers);
ммм... numbers - это не выражение. И что ты имеешь ввиду под расширяет?

2022-02-17 07:53 UTC, Alkirys requested changes

2022-02-17 07:53 UTC, Alkirys commented on tests/minmax.js
> +    });
предположим, что тебе входные данные приходят с бэка и из-за какого-то недопонимания пришла не строка. Обрати внимание на такие кейсы

2022-02-17 19:53 UTC, rinatkh commented on source/minmax.js
> +'use strict';
Он не даёт системе закрывать глаза на ошибки, выдавая соответствующие исключения. Это приводит к остановке выполнения программ.

2022-02-17 20:06 UTC, rinatkh commented on source/minmax.js
> +    let max = Math.max(...numbers);
аргументов для вызовов функций равно нулю или больше нуля

2022-02-18 11:47 UTC, Alkirys requested changes
Отлично, это решение выглядит гораздо лучше) но совершенству нет предела, так что, у меня есть еще несколько замечаний
А еще ты все еще не учел тест-кейсы, в которых приходят невалидные с точки зрения типа данные

2022-02-18 11:47 UTC, Alkirys commented on source/minmax.js
> +    numbers.forEach((item) => {
в данном случае тоже можно использовать const, потому что ссылка на сам объект массива не изменяется. let нужно было бы писать, если бы ты потом записал в arr_digits какой-то другой массив

2022-02-18 11:47 UTC, Alkirys commented on source/minmax.js
> +    }
мне кажется, вот так будет выглядеть нагляднее, как считаешь?
```
return [
    Math.min.apply(null, arr_digits),
    Math.max.apply(null, arr_digits),
];
```

2022-02-18 11:47 UTC, Alkirys commented on source/minmax.js
> +    }
круто, что ты знаешь про apply, но чем обусловлено ее использование тут? Почему ты решил заменить spread оператор на apply?

2022-02-18 11:51 UTC, Alkirys commented on source/minmax.js
> +    let max = Math.max(...numbers);
так... а можешь теперь весь первый абзац с mdn, из которого ты скопировал ответ пересказать своими словами?😉

2022-02-18 13:02 UTC, rinatkh commented on source/minmax.js
> +    }
В данном случае, у них одинаковая цель. Просто apply использовует элементы  в качестве аргументов функции нежели, чем spread

2022-02-18 13:02 UTC, rinatkh commented on tests/minmax.js
> +    });
исправил

2022-02-18 13:03 UTC, rinatkh commented on source/minmax.js
> +    numbers.forEach((item) => {
исправил

2022-02-18 13:05 UTC, rinatkh commented on source/minmax.js
> +    let max = Math.max(...numbers);
Данный оператор позволяет вносить в себя стольоко аргументов функции, сколько хочется. То есть для каждого аргумента не нужно писать свое название в аргументах функции

2022-02-18 13:38 UTC, Alkirys requested changes

2022-02-18 13:38 UTC, Alkirys commented on source/minmax.js
> +    }
немного странное условие !(a = b). Давай упростим)

2022-02-18 13:38 UTC, Alkirys commented on tests/minmax.js
> +    });
этот тест проверяет не только то, как себя ведет ф-ция, когда в нее передают спец символы, но и как она себя ведет, когда в нее поступает только одно валидное значение. Предлагаю разнести эти проверки на 2 разных тест-кейса

2022-02-18 13:38 UTC, Alkirys commented on tests/minmax.js
> +    });
тут чет отступы поехали(

2022-02-18 13:38 UTC, Alkirys commented on tests/minmax.js
> +    });
Не нужно думать, что если что-то очевидно, другие также считает это очевидным. Такой подход со временем может привести к ошибкам. В данном случае, конечно, условие простое, но если бы оно было сложнее и в будущем например кто-то дополнял твой код, поменял это условие и допустил в нем ошибку, было бы лучше, чтобы тесты эту ошибку обнаружили. 
Поэтому лучше добавь еще несколько проверок на остальные примитивы

2022-02-18 13:38 UTC, Alkirys commented on source/minmax.js
> +            arrDigits.push(item);
еще небольшой комментарий. Внутри forEach и подобных ф-ций лучше давать переменным более конкретные имена. Так код выглядит понятнее:
```
wildCats.forEach((cat) => {
    cat.sayMeow();
});
```
Пример надуманный, но уверен, ты понял, о чем я)

2022-02-18 13:39 UTC, Alkirys commented on source/minmax.js
> +    }
тогда я не очень понимаю, зачем ты заменил краткий и более красивый синтаксис spread на apply

2022-02-18 14:02 UTC, rinatkh commented on source/minmax.js
> +    }
исправил

2022-02-18 14:03 UTC, rinatkh commented on tests/minmax.js
> +    });
исправил

2022-02-18 14:03 UTC, rinatkh commented on tests/minmax.js
> +    });
исправил

2022-02-18 14:03 UTC, rinatkh commented on source/minmax.js
> +            arrDigits.push(item);
исправил

2022-02-18 14:03 UTC, rinatkh commented on source/minmax.js
> +    }
исправил

2022-02-18 15:23 UTC, Alkirys requested changes

2022-02-18 15:23 UTC, Alkirys commented on source/minmax.js
> +    }
так же, как в случае с == и ===, в js есть != и !==

2022-02-18 15:23 UTC, Alkirys commented on tests/minmax.js
> +        assert.deepEqual(minmax({name: "json"}), [undefined, undefined]);
я бы еще проверил на undefined во входных данных. Это одна из самых вероятных ошибок с данными, которые могут случиться

2022-02-18 15:23 UTC, Alkirys commented on source/minmax.js
> +}
стрелочная функция объявляется как переменная, и в конце объявления тоже нужна ;

2022-02-18 15:29 UTC, Alkirys approved these changes

2022-02-18 21:21 UTC, closed without merging