Медников Роман, Вариант 17
frontend-park-mail-ru/homework_2022_1 pull request #36
Opened 2022-02-14 20:43 UTC by kllmagn

2022-02-15 15:05 UTC, DPeshkoff requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

2022-02-15 15:05 UTC, DPeshkoff commented on source/plainify.js
> +    }
Мне кажется, это будет лучше сделать, используя специализированные методы массивов ([например](https://learn.javascript.ru/array-methods#filter))

2022-02-15 15:05 UTC, DPeshkoff commented on source/plainify.js
> +        let prop = parent ? parent + '.' + k : k;
Если не изменяешь - то лучше пиши `const`)

2022-02-15 15:05 UTC, DPeshkoff commented on source/plainify.js
> +function plainify(obj, parent, out = {}){
Давай избавимся от out и проверим все остальные аргументы)

2022-02-15 15:05 UTC, DPeshkoff commented on source/plainify.js
> +
По требованиям задания к функции нужна документация [JSDoc](https://jsdoc.app), добавь, пожалуйста

2022-02-15 15:05 UTC, DPeshkoff commented on tests/plainify.js
> -		assert.deepEqual(plainify({foo: 'bar', baz: 42}), {'foo': 'bar', 'baz': 42});
Не нужно исправлять оригинальные тесты)

2022-02-15 15:05 UTC, DPeshkoff commented on tests/plainify.js
> +		const nested4 = {
Излишнее, как мне кажется, лучше добавить тесты на некорректный ввод

2022-02-16 14:50 UTC, kllmagn commented on source/plainify.js
> +'use strict';
Для того, чтобы включить строгий режим выполнения кода, т.е. чтобы ограничить синтаксис языка и производить вывод сообщений об исключениях. Думаю второе нам как раз и нужно в тестах.

2022-02-16 21:09 UTC, DPeshkoff requested changes
Привет!
Нужно кое-что поправить в решении:

2022-02-16 21:09 UTC, DPeshkoff commented on source/plainify.js
> +    if (typeof obj != 'object' || Array.isArray(obj) || obj == null) return obj;
Лучше [строгое сравнение](https://learn.javascript.ru/comparison#strogoe-sravnenie)

Для читаемости лучше `return obj` в блок {} и на новую строчку)

`obj == null` лучше заменить на более [краткую проверку](https://developer.mozilla.org/ru/docs/Glossary/Falsy)

И лучше выбрасывать ошибку)

2022-02-16 21:09 UTC, DPeshkoff commented on source/plainify.js
> +        else res[k] = obj[k];
Какие-то очень страшные циклы(
Давай попробуем это привести к массиву и применить [более удобные возможности языка](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

2022-02-16 21:10 UTC, DPeshkoff commented on source/plainify.js
> +function plainify(obj, parent, out = {}){
Кстати, а можешь, пожалуйста, рассказать, в чем разница обычных функций и стрелочных?)

2022-02-17 03:08 UTC, kllmagn commented on source/plainify.js
> +function plainify(obj, parent, out = {}){
Стрелочные функции могут быть анонимными (не иметь привязанного имени переменной), также они более простые и короткие, что позволяет определять их однострочно, в свою очередь обычные функции имеют собственное значение this (в некоторых случаях это контекст данной функции).

2022-02-17 03:15 UTC, kllmagn commented on source/plainify.js
> +function plainify(obj, parent, out = {}){
Еще если опустить фигурные скобки у тела стрелочной функции, то функция вернет выражение и без наличия return.

2022-02-17 22:47 UTC, DPeshkoff requested changes

2022-02-17 22:47 UTC, DPeshkoff commented on source/plainify.js
> +    });
Можно еще круче, если попробовать reduce)

2022-02-17 22:47 UTC, DPeshkoff commented on source/plainify.js
> +        throw new Error("Unsupported argument");
лучше TypeError

2022-02-18 18:51 UTC, DPeshkoff requested changes

2022-02-18 18:59 UTC, DPeshkoff requested changes

2022-02-18 18:59 UTC, DPeshkoff commented on source/plainify.js
> +        var [propKey, propVal] = prop;
лучше `let`

Можешь, пожалуйста, рассказать, в чем между ними разница?

2022-02-18 18:59 UTC, DPeshkoff commented on source/plainify.js
> +    {
тут тоже {
}

2022-02-18 18:59 UTC, DPeshkoff commented on source/plainify.js
> +        {
и тут {
}

2022-02-18 19:09 UTC, kllmagn commented
'use strict' включает строгий режим, который ограничивает синтаксис кода, ошибки, которые ранее могли бы быть проигнорированы, выбрасываются в виде исключения, тем самым повышая безопасность написанного кода

2022-02-18 19:22 UTC, DPeshkoff approved these changes

2022-02-18 21:24 UTC, closed without merging