Каташинский Кирилл WEB-21 Вариант 10
frontend-park-mail-ru/homework_2022_1 pull request #4
Opened 2022-02-05 17:39 UTC by kirill555101

2022-02-07 16:35 UTC, SPetrenko17 commented
Добрейший вечерочек. Я ментор Сережа. Рад приветствовать на самом ярком семестре технопарка. В ближайшие несколько итераций я буду проводить ревью твоего ДЗ0. Если ты видишь это сообщение и хочешь закрыть компьютер, то рекомендую перехотеть и поправить замечания...

2022-02-07 17:31 UTC, SPetrenko17 commented on tests/letters.js
> +	QUnit.test('Работает с объектом String', function (assert) {
Вроде как ты покрыл все тест-кейсы. Го в качестве практически-теоретического задания ты добавишь побольше тест-кейсов с проверкой объекта String

2022-02-07 17:36 UTC, SPetrenko17 commented on source/letters.js
> +    throw Error('The first argument must be string');
Предлагаю еще вынести тексты ошибок в отдельные константы. Вдруг потом пригодятся...

2022-02-08 16:43 UTC, SPetrenko17 commented on source/letters.js
>  const letters = (inputString, isFirstSymbolRepeated) => {
По коду все ок. Можешь ли ты мне ответить на пару вопросов? После хорошего ответа поставлю ОК от ментора.
1. Твоя функция принимает два аргумента. В случае, если бы тебе не понадобился дефолтный кейс c isFirstSymbolRepeated = undefined , то как бы ты мог решить эту задачу?

2. Почему у тебя две проверки в кейсе обработки ошибки ARGUMENT_IS_NOT_STRING_ERROR?

2022-02-08 16:57 UTC, kirill555101 commented on source/letters.js
>  const letters = (inputString, isFirstSymbolRepeated) => {
1. Через аргументы по умолчанию. Например, задав isFirstSymbolRepeated = null в заголовке функции.
2. Добавил две проверки, потому что у меня в первом аргументе может приходить как переменная строковая, так и объект String с таким же поведением, но у которого typeof не возвращает string.

2022-02-08 17:06 UTC, SPetrenko17 commented on source/letters.js
>  const letters = (inputString, isFirstSymbolRepeated) => {
Ответ принят) Удачи на самом лучшем семе тп!

2022-02-11 21:54 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

хорошо решил задачу, молодец :) есть несколько комментов небольших и вопрос "на засыпку": ты использовал `indexOf` для получения индекса элемента, а знаешь ли ты про другие методы получения/проверки индекса? расскажи про них кратко, а также попытайся аргументировать, почему здесь корректно использовал именно этот.

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

2022-02-11 21:54 UTC, Betchika99 commented on source/letters.js
> +  }
давай добавим пустую строку для отделения логических блоков. почитай подробнее про код-стайл [в этой статье](https://learn.javascript.ru/coding-style)

2022-02-11 21:54 UTC, Betchika99 commented on source/letters.js
> +const letters = (inputString, isFirstSymbolRepeated) => {
обычно аргументы, которые опциональны, изначально инициализируют, чтобы в коде не проверять на undefined. Это называется параметрами по умолчанию, подробнее можешь почитать [здесь](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Default_parameters). Давай добавим здесь `isFirstSymbolRepeated = true (или false, как больше нравится)`, чтобы не делать лишнюю проверку дальше в коде

2022-02-11 21:54 UTC, Betchika99 commented on source/letters.js
> +          return self.indexOf(item) === self.lastIndexOf(item);
когда этот кейс возможен?

2022-02-13 08:54 UTC, kirill555101 commented on source/letters.js
> +const letters = (inputString, isFirstSymbolRepeated) => {
Так у меня по заданию должно быть 3 условия: удаление всех символов, которые будут встречаться в строке более одного раза, оставить из этих символов только первый или оставить из этих символов только последний. Соответственно, если мы не передаем второй аргумент, то срабатывает первое условие, если передаем true, то второе, если передаем false, то третье.

2022-02-13 08:57 UTC, kirill555101 commented on source/letters.js
> +  }
Поправил

2022-02-13 09:10 UTC, kirill555101 commented
> привет)) добро пожаловать на курс по Фронтенду))))
> 
> хорошо решил задачу, молодец :) есть несколько комментов небольших и вопрос "на засыпку": ты использовал `indexOf` для получения индекса элемента, а знаешь ли ты про другие методы получения/проверки индекса? расскажи про них кратко, а также попытайся аргументировать, почему здесь корректно использовал именно этот.
> 
> если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)
> 
> после того, как поправишь, напиши здесь коммент "Готово" плз :)

Например, через Array.prototype.findIndex(). Он возвращает индекс в массиве, если элемент удовлетворяет условию проверяющей функции. В противном случае возвращается -1.

Я использовал indexOf, поскольку он возвращает первый элемент, удовлетворяющий условию, что в моем случае оказалось самым правильным. Соответственно lastIndexOf я использовал для поиска последнего элемента, удовлетворяющего условию.

2022-02-13 09:18 UTC, kirill555101 commented
Готово

2022-02-13 11:07 UTC, closed without merging