Variant 14
frontend-park-mail-ru/homework_2022_1 pull request #5
Opened 2022-02-05 23:50 UTC by NNKulickov

Куликов Николай

2022-02-06 13:14 UTC, Sarafa2n requested changes
Привет! Поздравляю с переходом на курс фронтенда. Ты хорошо справился с дз, но у меня нашлось пара замечаний. Если что-то не понятно будет ты пиши, подскажу

2022-02-06 13:14 UTC, Sarafa2n commented on source/set.js
> +            return object
В forEach нет возвращаемого значения, оно просто закончит выполнение шага данного https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

Если ты хотел что-то вернуть то лучше использовать другой метод к примеру`reduce`

2022-02-06 13:14 UTC, Sarafa2n commented on source/set.js
> +        if (typeof result[key] == 'object'){ // check
Такая проверка не совсем корректна так как у тебя объектом может быть что угодно.
Посмотри что выдаст тебе `typeof new Array(1, 10) === 'object'`

2022-02-06 13:14 UTC, Sarafa2n commented on source/set.js
> +        if (!result[key]){ // doesn't exists - create new object & switch pointer
Посмотри какой есть метод у объекта который проверяет есть ли данное свойство

2022-02-06 13:14 UTC, Sarafa2n commented on source/set.js
> +    let result = object
лучше назвать `buff` так как ты ее не возвращаешь

2022-02-06 13:14 UTC, Sarafa2n commented on source/set.js
> +    path.split(".").slice(1).forEach((key, index, arr) => {
Давай использовать одинарные кавычки

2022-02-06 13:14 UTC, Sarafa2n commented on tests/set.js
> +
А что будет если я не валидные данные кину в функцию?

2022-02-06 13:17 UTC, NNKulickov commented on source/set.js
> +const set = (object, path, value) => {
Такой же function expression с явным указанием функции:

2022-02-06 13:24 UTC, NNKulickov commented on source/set.js
> +            return object
В этом и была идея. Это условие выходит из функции целиком, потому что был обработан последний ключ.

2022-02-06 14:20 UTC, NNKulickov commented on tests/set.js
> +
Добавил валидацию данных. Написал тесты

2022-02-06 14:20 UTC, NNKulickov commented on source/set.js
> +    path.split(".").slice(1).forEach((key, index, arr) => {
Исправил

2022-02-06 14:21 UTC, NNKulickov commented on source/set.js
> +    let result = object
Исправил

2022-02-06 14:21 UTC, NNKulickov commented on source/set.js
> +        if (!result[key]){ // doesn't exists - create new object & switch pointer
Исправил с использование метода hasOwnProperty

2022-02-06 14:27 UTC, NNKulickov commented on source/set.js
> +        if (typeof result[key] == 'object'){ // check
Здесь происходит проверка, что тип данных явяляется указателем, потому что переходы по вложенностям осуществляются по ним. Массив в js обладает свойствами объекта, поэтому и выдает true при сравнении и также является указателем.

2022-02-06 14:34 UTC, NNKulickov commented on source/set.js
> +        if (typeof result[key] == 'object'){ // check
Убрал эту проверку, поскольку ранее уже создается свойство с пустым объектом.

2022-02-07 09:56 UTC, Sarafa2n requested changes

2022-02-07 09:56 UTC, Sarafa2n commented on source/set.js
> +        object = {};
Давай писать if с {}

2022-02-07 09:56 UTC, Sarafa2n commented on source/set.js
> +        return object;
тут тоже

2022-02-07 14:45 UTC, NNKulickov commented on source/set.js
> +        object = {};
Исправил

2022-02-07 14:45 UTC, NNKulickov commented on source/set.js
> +        return object;
Исправил

2022-02-08 08:27 UTC, Sarafa2n requested changes

2022-02-08 08:27 UTC, Sarafa2n commented on source/set.js
> +    }
Лучше ошибку кидать, через `throw`

2022-02-08 09:01 UTC, NNKulickov commented on source/set.js
> +    }
Добавил ошибки

2022-02-08 09:07 UTC, Sarafa2n requested changes

2022-02-08 09:07 UTC, Sarafa2n commented on source/set.js
> +    }
ну тут не только ошибка что не точки может передана была пустая строка. Лучше написать не валидный ключ

2022-02-08 10:34 UTC, NNKulickov commented on source/set.js
> +    }
исправил

2022-02-08 13:24 UTC, Sarafa2n requested changes

2022-02-08 13:24 UTC, Sarafa2n commented on source/set.js
> +    const buffObject = keys.slice(1,-1).reduce((accumulator,key) => {
давай добавим отступы, а то сливается

2022-02-08 13:30 UTC, NNKulickov commented on source/set.js
> +    const buffObject = keys.slice(1,-1).reduce((accumulator,key) => {
добавил

2022-02-08 13:42 UTC, Sarafa2n requested changes

2022-02-08 13:42 UTC, Sarafa2n commented on source/set.js
> +        object = {};
Давай тут тоже высылать ошибку, и добавь проверку что у тебя объект пришел

2022-02-08 15:23 UTC, Sarafa2n requested changes

2022-02-08 15:50 UTC, NNKulickov commented on source/set.js
> +    if (keys.at(-1) === '' || keys.length === 1){
Последний ключ. Добавил

2022-02-08 18:31 UTC, Sarafa2n requested changes

2022-02-08 18:31 UTC, Sarafa2n commented on tests/set.js
> +            });
а можно же проверить какое сообщение вернет, так надежнее, а то вдруг оно падает не на той проверке, которой ты ожидаешь 
https://nodejs.org/api/assert.html#assertthrowsfn-error-message

2022-02-08 22:34 UTC, NNKulickov commented on tests/set.js
> +            });
Исправил

2022-02-09 08:12 UTC, Sarafa2n requested changes

2022-02-09 08:12 UTC, Sarafa2n commented on tests/set.js
> +			Error("it is not an object!"));
чет с табами, вынеси ошибку в отдельную переменную, чтобы не копипастить

2022-02-09 08:19 UTC, Sarafa2n requested changes

2022-02-09 08:19 UTC, Sarafa2n commented on tests/set.js
> +		    error3 = Error("invalid path!")
хм, опять табы

2022-02-09 08:56 UTC, Sarafa2n approved these changes

2022-02-11 22:24 UTC, Betchika99 requested changes
привет)) рада видеть тебя на нашем курсе)

ты хорошо справился с заданием, но у меня есть несколько небольших замечаний, после которого твой код будет просто супер классный)

- [ ] обрати внимание на смысловую нагрузку валидации. пока она вызывает вопросы (см. комменты)
- [ ] внимательно ознакомься с доком код-стайла и примени советы оттуда во **всем ДЗ**

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-11 22:24 UTC, Betchika99 commented on source/set.js
> +    if( !object || object.constructor.name !== 'Object'){
тут и далее перед { нужен пробел. давай придерживаться код-стайла (подробнее [тут](https://learn.javascript.ru/coding-style))

2022-02-11 22:24 UTC, Betchika99 commented on source/set.js
> + * @param {object} value - the value of the attribute to set.
почему здесь тип object?

2022-02-11 22:24 UTC, Betchika99 commented on source/set.js
> +          lastKey = keys.at(-1);
давай для лучшей читаемости вторую переменную объявим на новой строке с новым `const`)

2022-02-11 22:24 UTC, Betchika99 commented on source/set.js
> +    const keys = path.split('.'),
давай здесь сразу отфильтруем первое значение, если оно - пустая строка (если path начинается с точки)

2022-02-11 22:24 UTC, Betchika99 commented on source/set.js
> +    if ( lastKey === '' || keys.length === 1){
в каком случае lastKey будет пустой строкой? кажется, лучше на этапе сплитинга строки path исключать весь "мусор" и проверять входные данные там, а не lastKey

2022-02-11 22:24 UTC, Betchika99 commented on source/set.js
> +    }, object);
любая функция, которую мы пишем, должна быть чистой. поэтому модифицировать исходный объект - плохая практика. лучше создать копию

2022-02-11 22:24 UTC, Betchika99 commented on tests/set.js
> +		const error3 = Error("invalid path!");
давай везде использовать одинаковые кавычки. в этом документе они одинарные

2022-02-12 01:03 UTC, NNKulickov commented on source/set.js
> +    if( !object || object.constructor.name !== 'Object'){
Готово

2022-02-12 01:05 UTC, NNKulickov commented on source/set.js
> + * @param {object} value - the value of the attribute to set.
Исправил на *(любой тип). Предполагается, что можно передать любое значение в качестве устанавливаемого

2022-02-12 01:06 UTC, NNKulickov commented on source/set.js
> +    const keys = path.split('.'),
Готово

2022-02-12 01:07 UTC, NNKulickov commented on source/set.js
> +    if ( lastKey === '' || keys.length === 1){
Готово

2022-02-12 10:48 UTC, NNKulickov commented
Готово

2022-02-12 11:24 UTC, Betchika99 approved these changes

2022-02-12 11:24 UTC, closed without merging