Майцветов Владислав, Вариант 16
frontend-park-mail-ru/homework_2022_1 pull request #6
Opened 2022-02-06 19:14 UTC by Mausved

2022-02-07 09:34 UTC, Sarafa2n requested changes
Привет! Добро пожаловать на курс фронтенда. Ты не плохо сделал дз0 но есть пара мест где стоит поправить. Кажется можно упростить решение

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +let format = (numbers, columns) => {
Во-первых `const`
Во-вторых круто что используешь стрелочные функции

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +    if (isNaN(+columns)) {
Уверен что нужно использовать isNaN ? Посмотри тут как это работает https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/isNaN

Чтобы проверить что это число есть другие способы

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +        let widths = Array()
1. `const`
2. `new Array() ` или `[]`

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +    const countWidthsEveryColumn = (numbers, columns) => {
Давай вынесем функции из format

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +        }
Поиск длины в колонке можно сделать проще. Посмотри в сторону использования `reduce`

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +        let formattedRow = String();
Аналогично с `Array`

2022-02-07 09:34 UTC, Sarafa2n commented on source/format.js
> +            }
Кажется такое лучше делать в самом начале. Не очень делать проверку валидности данных в конце.

2022-02-07 18:27 UTC, Mausved commented on source/format.js
> +        let formattedRow = String();
заменил `String()` на обратные ковычки.

2022-02-07 18:27 UTC, Mausved commented on source/format.js
> +            }
перенес. Валидация теперь выполняется при подсчете ширины.

2022-02-07 18:28 UTC, Mausved commented on source/format.js
> +        }
сделал через `reduce()`, сама логика подсчета занимает три строчки, но из-за валидации объем не особо уменьшился.

2022-02-07 18:29 UTC, Mausved commented on source/format.js
> +    const countWidthsEveryColumn = (numbers, columns) => {
убрал `function expression` для подсчета ширины, функцию форматирования вынес. (Возможно не до конца правильно понял, и нужно убрать отдельные функции вообще).

2022-02-07 18:29 UTC, Mausved commented on source/format.js
> +        let widths = Array()
Заменил на `[]`

2022-02-07 18:30 UTC, Mausved commented on source/format.js
> +let format = (numbers, columns) => {
1) добавил квалификатор `const`
2) спасибо)

2022-02-08 08:32 UTC, Sarafa2n requested changes

2022-02-08 08:32 UTC, Sarafa2n commented on source/format.js
> +        return undefined;
лучше ошибку выкидывать

2022-02-08 08:32 UTC, Sarafa2n commented on source/format.js
> +    numbers.reduce(function (prevNumber, currentNumber, currentNumberIndex) {
может стрелочную ? 
У тебя не совсем верный нейминг `prevNumber` это аккумулятор

2022-02-08 08:32 UTC, Sarafa2n commented on source/format.js
> +        // alert(`check values: ${prevNumber} - ${currentNumber}`);
что за комментарий?

2022-02-08 08:32 UTC, Sarafa2n commented on source/format.js
> +        }
зачем? если ты и хочешь проверить что внутри массива все хорошо, лучше проверить не тут посмотри в сторону использования для этого `.filter()`

2022-02-08 08:32 UTC, Sarafa2n commented on source/format.js
> +    return (okStatus) ? setFormat(numbers, columns, widths) : undefined;
не совсем понял, можешь пояснить

2022-02-08 08:32 UTC, Sarafa2n commented on source/format.js
> +    for (let number of numbers) {
а может возьмем какой-нибудь метод ?

2022-02-08 10:32 UTC, Mausved commented on source/format.js
> +        // alert(`check values: ${prevNumber} - ${currentNumber}`);
Сори, дебажжил просто

2022-02-08 10:39 UTC, Mausved commented on source/format.js
> +    return (okStatus) ? setFormat(numbers, columns, widths) : undefined;
Reduce() просто начинает с индекса '1', приходится нулевой элемент отдельно проверять.

2022-02-08 14:27 UTC, Mausved commented on source/format.js
> +        return undefined;
исправил. Теперь бросает исключение.

2022-02-08 14:28 UTC, Mausved commented on source/format.js
> +    numbers.reduce(function (prevNumber, currentNumber, currentNumberIndex) {
переименовал, добавил стрелочную.

2022-02-08 14:28 UTC, Mausved commented on source/format.js
> +        // alert(`check values: ${prevNumber} - ${currentNumber}`);
убрал.

2022-02-08 14:28 UTC, Mausved commented on source/format.js
> +        }
использую `.every()` для валидации

2022-02-08 14:29 UTC, Mausved commented on source/format.js
> +    for (let number of numbers) {
взял `map()`

2022-02-08 18:28 UTC, Sarafa2n requested changes

2022-02-08 18:28 UTC, Sarafa2n commented on source/format.js
> +        throw new SyntaxError('Данные некорректны');
давай сделаем чтобы у нас проверка была с новой строки, читаемость лучше

2022-02-08 18:28 UTC, Sarafa2n commented on source/format.js
> +    });
а точно дешевле нельзя, нельзя два отдельных цикла?

2022-02-08 21:30 UTC, Sarafa2n requested changes

2022-02-08 21:30 UTC, Sarafa2n commented on source/format.js
> +    if (typeof (numbers) !== 'object' ||
вот тут тоже надо перенести на новую строку

2022-02-08 21:30 UTC, Sarafa2n commented on source/format.js
> +        throw new SyntaxError('Данные некорректны');
кажется таб поехал

2022-02-09 08:07 UTC, Sarafa2n requested changes

2022-02-09 08:07 UTC, Sarafa2n commented on source/format.js
> +        throw new SyntaxError('Данные некорректны');
Лучше просто Error
Почитай почему это не совсем правильно https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError

2022-02-09 08:40 UTC, Mausved commented on source/format.js
> +        throw new SyntaxError('Данные некорректны');
перенес.

2022-02-09 08:40 UTC, Mausved commented on source/format.js
> +    });
переделал.

2022-02-09 08:40 UTC, Mausved commented on source/format.js
> +    if (typeof (numbers) !== 'object' ||
перенес.

2022-02-09 08:44 UTC, Mausved commented on source/format.js
> +        throw new SyntaxError('Данные некорректны');
Исправил на `Error`.

2022-02-09 08:58 UTC, Sarafa2n commented on source/format.js
> +      typeof (numbers) !== 'object' ||
Может лучше проверить что это массив есть специальный метод

2022-02-09 09:22 UTC, Sarafa2n approved these changes

2022-02-12 11:52 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

ты не плохо справился с заданием, молодец :) но есть несколько небольших замечаний и вопрос "на засыпку": расскажи всё, что знаешь, про работу с числами в JS (какие есть типы, как в коде можно проверить, как сравниваются числа и не числа и т.п.). Коротко и по делу :)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-12 11:52 UTC, Betchika99 commented on source/format.js
> + * @param {object} numbers - input numerical array.
почему тип object? ты же массив принимаешь. посмотри повнимательнее [документацию](https://jsdoc.app/tags-param.html)

2022-02-12 11:52 UTC, Betchika99 commented on source/format.js
> +      !numbers.every(number => !Number.isNaN(+number))
по заданию числа должны быть целыми)

2022-02-12 11:52 UTC, Betchika99 commented on source/format.js
> +      !numbers.every(number => !Number.isNaN(+number))
почему бы вместо !every не использовать some?)

2022-02-12 11:52 UTC, Betchika99 commented on source/format.js
> +const format = (numbers, columns) => {
давай переименуем columns => count или как-то так, чтобы понимать, что это количество, а то дальше по коду плохо читается смысл этой переменной

2022-02-12 11:52 UTC, Betchika99 commented on source/format.js
> +        }
давай попробуем использовать здесь конкатенацию через шаблонные строки (подробнее можешь почитать [здесь](https://dev-gang.ru/article/-sposoba-obedinenija-strok-v-javascript-prgtacj4yl/)

2022-02-12 12:08 UTC, Mausved commented on source/format.js
> + * @param {object} numbers - input numerical array.
исправил на int[]

2022-02-12 12:09 UTC, Mausved commented on source/format.js
> +      !numbers.every(number => !Number.isNaN(+number))
исправил на `some()`

2022-02-12 12:11 UTC, Mausved commented on source/format.js
> +const format = (numbers, columns) => {
исправил на `columnsAmount`, что переводится как `количество колонок`

2022-02-12 12:17 UTC, Mausved commented on source/format.js
> +        }
изменил через конкатенацию шаблонных строк)

2022-02-12 12:42 UTC, Mausved commented
Готово

2022-02-12 12:56 UTC, Mausved commented
Готово

2022-02-12 12:57 UTC, Mausved commented on source/format.js
> +      !numbers.every(number => !Number.isNaN(+number))
> по заданию числа должны быть целыми)

добавил проверку `Number.isInteger()`

2022-02-12 12:59 UTC, Betchika99 commented
> Привет! Числа в `JS` выражаются типом `Number`. Диапазон у такого типа равен `+- (2^53 -1)`, если не хватает этого диапазона, то используется тип произвольной длины `BigInt`. Для чисел предусмотрены самые популярные операторы `+`, `-`, `/`, `%`, `*`, `=`, операции сравнения `>=`, `<=`, `==`, `!=`, `<`, `>`, `===`, `!==`.
> 
> При `суммировании числового типа и строкового`, **числовой приводится к строковому.** При `разности числового типа и строкового`, **строковой приводится к числовому.** При `сравнении числового типа и нечислового`, **второй приводится к числовому типу.** Если приведение не удалось, то нечисловой тип принимает значение `NaN`. `undefined` --> **NaN**; `null` --> **0**; `Пустая строка` --> **0**; `true/false` --> **1/0**;
> 
> "Быстрый" способ преобразовать объект в число - добавление унарного `+` перед объектом (`65 === +"65"`).
> 
> Чтобы проверить, является ли число корректным используются функции `isNaN()` (менее безопасная при приведении типов) и `Numbers.isNaN()` (более безопасная при приведении типов).
> 
> Также есть математическая бесконечность `Infinity`, которой справедливы все математические выводы и суждения (`5/0 === Infinity`).

а что насчет разных типов чисел? целые, вещественные? как они себя ведут? как их можно отличить друг от друга в джс?

2022-02-12 13:08 UTC, Mausved commented
> > Привет! Числа в `JS` выражаются типом `Number`. Диапазон у такого типа равен `+- (2^53 -1)`, если не хватает этого диапазона, то используется тип произвольной длины `BigInt`. Для чисел предусмотрены самые популярные операторы `+`, `-`, `/`, `%`, `*`, `=`, операции сравнения `>=`, `<=`, `==`, `!=`, `<`, `>`, `===`, `!==`.
> > При `суммировании числового типа и строкового`, **числовой приводится к строковому.** При `разности числового типа и строкового`, **строковой приводится к числовому.** При `сравнении числового типа и нечислового`, **второй приводится к числовому типу.** Если приведение не удалось, то нечисловой тип принимает значение `NaN`. `undefined` --> **NaN**; `null` --> **0**; `Пустая строка` --> **0**; `true/false` --> **1/0**;
> > "Быстрый" способ преобразовать объект в число - добавление унарного `+` перед объектом (`65 === +"65"`).
> > Чтобы проверить, является ли число корректным используются функции `isNaN()` (менее безопасная при приведении типов) и `Numbers.isNaN()` (более безопасная при приведении типов).
> > Также есть математическая бесконечность `Infinity`, которой справедливы все математические выводы и суждения (`5/0 === Infinity`).
> 
> а что насчет разных типов чисел? целые, вещественные? как они себя ведут? как их можно отличить друг от друга в джс?

Тип `Number` включает в себя как целые так и вещественные числа.
Для проверки на "целостность" числа используется функция `Number.isInteger()` и `Number.isSafeInteger()` (добавляются некоторые требования на безопасность числа), для проверки, что число является конечным используется `Number.isFinite()`.
При сравнении **вещественного и целого** последнее **приводится к вещественному и сравниваются**.

2022-02-12 13:08 UTC, Mausved commented
готово

2022-02-12 13:36 UTC, Betchika99 approved these changes

2022-02-12 13:37 UTC, closed without merging