Дмитрий Ильин, вариант 8
frontend-park-mail-ru/homework_2022_1 pull request #8
Opened 2022-02-06 21:45 UTC by Neytrinoo

2022-02-07 09:46 UTC, Sarafa2n requested changes
Привет! Поздравляю с переходом на курс фронтенда. Ты хорошо справился с дз0, но я нашел пару мест где надо поправить)

2022-02-07 09:46 UTC, Sarafa2n commented on source/sort.js
> +}
Эта функция используется только в одном месте, мог и не выносить)

2022-02-07 09:46 UTC, Sarafa2n commented on source/sort.js
> +}
Давай переделаем на стрелочную

2022-02-07 09:46 UTC, Sarafa2n commented on source/sort.js
> +    let new_words = [];
`const`

2022-02-07 09:46 UTC, Sarafa2n commented on source/sort.js
> + * @param str Input string
нет типа входных данных

2022-02-07 09:46 UTC, Sarafa2n commented on source/sort.js
> +    return new_words.sort(compare).join(' ');
а попробуй тут использовать `reduce` тогда и массив создавать будет не нужно

2022-02-07 09:46 UTC, Sarafa2n commented on source/sort.js
> +}
Добавь строку в конце файла, видишь тут  github ругается))

2022-02-07 09:46 UTC, Sarafa2n commented on tests/sort.js
> +		assert.strictEqual(sort('б'), 'Б', 'Работает с русским алфавитом');
Добавь тесты на невалидные данные

2022-02-07 15:19 UTC, Neytrinoo commented on source/sort.js
> +}
Переделал

2022-02-07 15:19 UTC, Neytrinoo commented on source/sort.js
> +    let new_words = [];
Поправил

2022-02-07 15:19 UTC, Neytrinoo commented on source/sort.js
> + * @param str Input string
Поправил

2022-02-07 15:20 UTC, Neytrinoo commented on source/sort.js
> +    return new_words.sort(compare).join(' ');
Немного не понял, как можно избавиться от доп массива. Мне нужно же сначала отсортировать буквы в словах, потом отсортировать сами слова и только потом склеить. Но убрал join и сделал редусе чисто чтобы было)

2022-02-07 15:20 UTC, Neytrinoo commented on source/sort.js
> +}
done

2022-02-07 15:21 UTC, Neytrinoo commented on tests/sort.js
> +		assert.strictEqual(sort('б'), 'Б', 'Работает с русским алфавитом');
done

2022-02-08 13:22 UTC, Sarafa2n requested changes

2022-02-08 13:22 UTC, Sarafa2n commented on source/sort.js
> +        let new_word = current.toLowerCase().split('').sort(compare).join('');
`const`

2022-02-08 13:22 UTC, Sarafa2n commented on source/sort.js
> +        return '';
давай лучше ошибку слать

2022-02-08 13:22 UTC, Sarafa2n commented on source/sort.js
> +const compare = (value1, value2) => {
давай добавим JSDOC и сюда

2022-02-08 18:19 UTC, Sarafa2n approved these changes

2022-02-12 12:26 UTC, Betchika99 requested changes
привет)) рада видеть тебя на нашем курсе))

хорошо решил задачу, молодец :) есть несколько небольших комментов и вопросов, чтобы понять, как хорошо ты разобрался в JS.

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-12 12:26 UTC, Betchika99 commented on source/sort.js
> +const COLLATOR = new Intl.Collator('ru');
круто, что ты изучил интернационализацию в JavaScript. Можешь коротко рассказать, что делает этот конструктор и механизм в целом? и зачем ты его используешь

2022-02-12 12:26 UTC, Betchika99 commented on source/sort.js
> +const sort = (str) => {
расскажи, почему нельзя использовать в этой задаче классический метод sort?

2022-02-12 12:26 UTC, Betchika99 commented on source/sort.js
> +        const new_word = current.toLowerCase().split('').sort(compare).join('');
в джс принято использовать camelCase

2022-02-12 12:26 UTC, Betchika99 commented on source/sort.js
> +        prev.push(new_word[0].toUpperCase() + new_word.slice(1));
давай воспользуемся конкатенацией строк через шаблонные строки. подробнее можешь почитать [здесь](https://dev-gang.ru/article/-sposoba-obedinenija-strok-v-javascript-prgtacj4yl/)

2022-02-12 12:26 UTC, Betchika99 commented on source/sort.js
> +    }, []).sort(compare).join(' ');
не возникнет ли такая ситуация: из-за того, что у тебя уже установлена у первого слова большая первая буква, то у него будет больше "вес" при сортировке? 
кажется, что лучше сортировать и работать со строкой в lower case, и только в конце преобразовывать первую букву

2022-02-12 14:27 UTC, Neytrinoo commented on source/sort.js
> +const COLLATOR = new Intl.Collator('ru');
Нуу этот конструктор создаст объект-сортировщик, который позволит нам сортировать данные в переданной ему локали. Ему можно передавать и другие параметры, которые будут настраивать сортировку как нам нужно, например можно определить, какой регистр будет приоритетным или задать игнорирование знаков пунктуации

2022-02-12 14:27 UTC, Neytrinoo commented on source/sort.js
> +const sort = (str) => {
Ну мы просто не сможем от него добиться нужной функциональности, нам нужно сперва преобразовать порядок букв в словах и только потом отсортировать сами слова

2022-02-12 14:27 UTC, Neytrinoo commented on source/sort.js
> +        const new_word = current.toLowerCase().split('').sort(compare).join('');
эх ох уж этот камел кейс не люблю его, но исправил

2022-02-12 14:27 UTC, Neytrinoo commented on source/sort.js
> +        prev.push(new_word[0].toUpperCase() + new_word.slice(1));
Исправил

2022-02-12 14:28 UTC, Neytrinoo commented on source/sort.js
> +    }, []).sort(compare).join(' ');
Не, я же у каждого слова делаю первую букву заглавной, так что на сортировку это не повлияет

2022-02-12 14:28 UTC, Neytrinoo commented on source/sort.js
> +    }, []).sort(compare).join(' ');
Готово)

2022-02-13 20:07 UTC, closed without merging