Variant 6
frontend-park-mail-ru/homework_2022_1 pull request #9
Opened 2022-02-07 00:09 UTC by Andrey123815

# Дьяконов Андрей

2022-02-07 00:10 UTC, Andrey123815 commented
# Дьяконов Андрей Вариант 6

2022-02-07 17:14 UTC, Tataklim commented
Добрейший вечерочек :)
Тепло приветствую тебя на курсе фронтенда!
Я буду проверять твою домашку - если появятся вопросы, обязательно задавай)

2022-02-07 17:24 UTC, Tataklim commented on source/tree.js
> +let final_string = ""
Сейчас у тебя эта переменная используется как глобальная - а поскольку ты ее в начале вызова функции не обнуляешь, результат может быть неверным в случае, если эта переменная как-то изменится в другой функции
Такой вариант был бы ок в рамках реализации класса, когда важно хранить состояние, здесь же стоит попробовать сделать иначе - просто в рамках функции

2022-02-07 17:24 UTC, Tataklim commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
Попробуй добавить к своим функциям  [JSDoc](https://jsdoc.app/) - это необходимо для документирования кода
Возможно, так их станет чуточку меньше и часть логики получится объединить

2022-02-07 17:24 UTC, Tataklim commented on source/tree.js
> +}
Попробуй найти и использовать функции работы со строками в js - так, чтобы избежать использования `for`

2022-02-07 17:24 UTC, Tataklim commented on source/tree.js
> +    final_string += "|";
Предлагаю почитать [правила](https://learn.javascript.ru/coding-style) оформления кода в js и исходя из прочитанного попробовать что-то поправить)
В частности - в js принято использовать одинарные кавычки

2022-02-07 17:24 UTC, Tataklim commented on tests/tree.js
> +    QUnit.test('Ёлочек с высотой нецелого типа не бывает', function (assert) {
Стоит подумать над тем, какие еще могут быть неподходящие входные параметры, учесть это в коде функции и тестах)
Также добавь, пожалуйста, еще тестов на валидные входные данные

2022-02-07 20:36 UTC, Tataklim commented on source/tree.js
> +'use strict';
Расскажи, для чего используешь эту строку?)

2022-02-07 20:36 UTC, Tataklim commented on source/tree.js
> +let final_string = ''
У тебя снова остается глобальная переменная - можно придумать весьма изощренные случаи (но все же можно!) того, как сломать этот код
Если хочется хранить в переменной - попробуй использовать, скажем, замыкания
Заодно будет отличной практикой :)

2022-02-07 20:36 UTC, Tataklim commented on source/tree.js
> +let final_string = ''
Также не совсем все поправил по кодстайлу, обрати внимание на:
- название переменных (в статье об этом вроде нет, но я уверена, ты сам это быстро найдешь)
- оформления стрелочных функций (чаще всего принято даже для одного аргумента брать его в круглые скобочки, а одну строку функции - в фигурные)

2022-02-07 20:36 UTC, Tataklim commented on source/tree.js
> +function drawSpaces(line_number, tree_size)  {
Также в случае использования замыканий не будет необходимости передавать часть параметров в функцию

2022-02-07 20:36 UTC, Tataklim commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
Ты используешь два вида объявления функций
Расскажи, какие ты знаешь еще?
Чем они принципиально отличаются?)

2022-02-07 20:36 UTC, Tataklim commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
Также есть ощущение, что оборачивать вызов в эту 'обертку', которая по факту ничего не делает - бессмысленно
Как вариант - здесь можно оставить валидацию входного параметра, в случае успеха - вызывать drawTree

2022-02-07 20:38 UTC, Tataklim commented
Еще кажется не добавил тест на валидные данные
Построй БОЛЬШУЮ ёлочку!!1

2022-02-07 21:02 UTC, Andrey123815 commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
> Еще кажется не добавил тест на валидные данные Построй БОЛЬШУЮ ёлочку!!1

Привет, не совсем понимаю что ты имела ввиду. Как связана валидация данных и большая елочка? Плюс насколько большую елочку нужно рассмотреть? И что подразумевается под валидацией данных? Я же сделал проверку на undefined и null в тестах. Все проходит

2022-02-07 21:12 UTC, Andrey123815 commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
> Ты используешь два вида объявления функций Расскажи, какие ты знаешь еще? Чем они принципиально отличаются?)

Существует три синтаксиса: Function Declaration, Function Expression и стреловидные функции. Стреловидные короче в записи, особенно удобны для однострочных функций. Первый синтаксис выделяется лучше при чтении кода чем второй, поэтому использовал именно его. Второй представляет собой создание переменной-функции, которую мы инициализируем одновременно с объявлением функции. Основная разница в том что Declaration доступно в любом месте, даже выше объявления, а второй тип только когда выполнение доходит до него.

2022-02-07 22:57 UTC, Andrey123815 commented on source/tree.js
> +'use strict';
Эта строка используется для указания интерпретатору работать с "строгом" (современном) режиме

2022-02-08 18:07 UTC, Tataklim commented on source/tree.js
> +    function drawLine(lineNumber) {
Может чуточку излишне - но кажется, что функция не рисует  линию, а добавляет ее к финальному результату

2022-02-08 18:13 UTC, Andrey123815 commented on source/tree.js
> +        }
Чтобы не передавать в них параметр lineNumber, могу вынести, как лучше сделать?

2022-02-08 18:15 UTC, Tataklim commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
> > Еще кажется не добавил тест на валидные данные Построй БОЛЬШУЮ ёлочку!!1
> 
> Привет, не совсем понимаю что ты имела ввиду. Как связана валидация данных и большая елочка? Плюс насколько большую елочку нужно рассмотреть? И что подразумевается под валидацией данных? Я же сделал проверку на undefined и null в тестах. Все проходит

Этот комментик относится к тому, что стоит добавить еще тест на подходящий (валидный) входной параметр - так, чтобы функция вернула елочку, а не null. Насколько большую - не принципиально вовсе, можно небольшую)
Валидацию ты сделал да, на невалидные данные тесты вижу, в этом плане все хорошо :)

2022-02-08 18:18 UTC, Tataklim commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
Теперь мини-вопросик про функции
Касаемо особенностей использования контекста в этих типах что можешь рассказать?)

2022-02-08 20:47 UTC, Tataklim commented on source/tree.js
> + * @param treeSize - требуемая высота ASCII-дерева.
Забыл про возвращаемое значение
Аналогично в функции `drawTree `

2022-02-08 20:47 UTC, Tataklim commented on source/tree.js
> +            let max_count_spaces = treeSize - 1;
!??!??!?!?

2022-02-08 20:47 UTC, Tataklim commented on source/tree.js
> +let drawTree = (treeSize) => {
Расскажи, в чем разница `let` и `const`?
Почему здесь и далее при объявлении функций (и некоторых переменных) используешь именно `let`?

2022-02-08 20:47 UTC, Tataklim commented on source/tree.js
> +     * @function Отрисовывает ASCII-дерево по горизонтальным линиям.
Раз уж заменили название функции на `addSmth` - стоит и JSDoc поправить :)

2022-02-08 20:47 UTC, Tataklim commented on source/tree.js
> +        }
Я бы вообще упразднила эти две функции
Дальше ведь внутри `addRoot ` ты не добавил отдельную функцию для создания пробелов

2022-02-08 20:52 UTC, Andrey123815 commented on source/tree.js
> +            let max_count_spaces = treeSize - 1;
Можно подсказку что значит этот комментарий? Что мне править?

2022-02-08 20:54 UTC, Andrey123815 commented on source/tree.js
> +let drawTree = (treeSize) => {
Ну вдруг я захочу как-то изменить функции. Но вообще да, стоило бы сделать const в рамках этого задания

2022-02-08 21:01 UTC, Tataklim commented on source/tree.js
> +let drawTree = (treeSize) => {
`const` - наша гарантия стабильности и безопасности)
Не стоит делать `let` 'на всякий случай'

2022-02-08 21:21 UTC, Tataklim commented on source/tree.js
> + * @param {number} treeSize - размер ASCII-дерева.
Необходимо добавить функциям [returns](https://jsdoc.app/tags-returns.html)

2022-02-08 21:21 UTC, Tataklim commented on source/tree.js
> +
Не нужно делать по 2 строки между объявлением функций, достаточно одной

2022-02-08 21:21 UTC, Tataklim commented on tests/tree.js
> +	});
Тут в файле разные отступы - стоит привести к единому виду

2022-02-08 21:27 UTC, Andrey123815 commented on tests/tree.js
> +	});
Разные отступы? А можешь пожалуйста указать на каких строках? Я просто взял скопировал один из тестов и сделал не на 5 а на 6. Отступы те же

2022-02-08 21:30 UTC, Tataklim commented on tests/tree.js
> +	});
Можешь посмотреть в дифе в гитхабе, где различия
<img width="673" alt="image" src="https://user-images.githubusercontent.com/36628483/153078876-68d122c1-5a0e-4dfb-bc2d-85fe74e2373d.png">
Возможно, что-то ты скопировал, где-то табами проставил
И у тебя в ide дефолтный таб содержит кол-во пробелов, отличное от того, которое у изначального автора задачи было

2022-02-08 21:45 UTC, Tataklim commented
Все равно с файлом тестов что-то не так(
Не нужно изменять отступы к уже существующим тестам - необходимо сделать твои написанные в том же стиле 
Также пройдись по моим незарезолвенным комментам - ещё осталось несколько нерешённых вопросов

2022-02-08 22:30 UTC, Andrey123815 commented on source/tree.js
> +const tree = tree_size => drawTree(tree_size);
Первые два типа отличаются от третьего тем, что стрелочные функции не имеют своего this. А при получении значения this оно как и обычная переменная берется из внешнего лексического окружения. this обычных функций не имеет значения до тех пор, пока функция не будет вызвана.

2022-02-08 22:31 UTC, Andrey123815 commented on tests/tree.js
> +	});
Исправил

2022-02-09 09:26 UTC, Tataklim commented
Попробуй еще разок пофиксить отступы :) Чтобы не было вот таких изменений в существующих тестах)
![image](https://user-images.githubusercontent.com/36628483/153164283-c5866d4b-c854-4c1b-8007-3a13968ac35e.png)
Понимаю, что это кажется бесполезной ерундой и зачастую в проектах есть линтер - но все же стоит обращать внимания на мелочи всегда
Потом передам на проверку дальше)

2022-02-09 10:27 UTC, Andrey123815 commented
> Все равно с файлом тестов что-то не так( Не нужно изменять отступы к уже существующим тестам - необходимо сделать твои написанные в том же стиле Также пройдись по моим незарезолвенным комментам - ещё осталось несколько нерешённых вопросов

Всё красное потому что я посмотрел как было в исходном файле с тестами (там размер таба равен 8), а я всё в прошлый раз переделал под 4
И сейчас исправил под тот стиль, который был в изначальном файле
Или я не совсем понял что ты имеешь ввиду

2022-02-09 12:04 UTC, Tataklim commented
> Всё красное потому что я посмотрел как было в исходном файле с тестами (там размер таба равен 8), а я всё в прошлый раз переделал под 4 И сейчас исправил под тот стиль, который был в изначальном файле Или я не совсем понял что ты имеешь ввиду

Если бы был тот же стиль, что был в изначально файле - изменений не было бы дифе
Диф показывается ведь относительно ветки, в которую ты сделал мр, а не относительно твоего изменения в каком-то коммите

2022-02-09 22:06 UTC, Andrey123815 commented
> > Всё красное потому что я посмотрел как было в исходном файле с тестами (там размер таба равен 8), а я всё в прошлый раз переделал под 4 И сейчас исправил под тот стиль, который был в изначальном файле Или я не совсем понял что ты имеешь ввиду
> 
> Если бы был тот же стиль, что был в изначально файле - изменений не было бы дифе сейчас Диф показывается ведь относительно ветки, в которую ты сделал мр, а не относительно твоего изменения в каком-то коммите

Исправил

2022-02-10 04:56 UTC, Tataklim commented
Отлично!
При решении домашки ты попробовал использовать замыкания, стрелочные функций и некоторые встроенные в js функции работы со строками - надеюсь, тебе это в дальнейшем поможет при реализации проекта :)
Хочется отметить, что для этой задачи использование замыканий можно отчасти отнести к оверинжинирингу. Это даже напоминает использование функциональных компонентов в реакте, но для практики на мой взгляд, попробовать можно)
Успехов тебе в дальнейшем обучении!

2022-02-12 19:12 UTC, Betchika99 requested changes
привет)) добро пожаловать на курс по Фронтенду))))

ты неплохо решил задачу, молодец :) отдельно хочу отметить, что ты хорошо декомпозируешь код, что делает его более читабельным. это тебе отлично поможет в будущем проекте.

есть несколько комментов к твоему коду, обрати на них внимание.
а еще поисследуй и расскажи про использование `this` в коде JS. что это за слово, за что оно отвечает, как мы можем его изменять. Коротко и по сути :)

если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)

после того, как поправишь, напиши здесь коммент "Готово" плз :)

2022-02-12 19:12 UTC, Betchika99 commented on source/tree.js
> +                !(treeSize % 1 === 0) || !treeSize) {
проверка `treeSize === undefined` лишняя, она подпадает под условие `!treeSize`. проверку на то, что treeSize - целое число лучше сделать другими способами (прочитай [про методы работы с числами](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number#methods) в JS)

2022-02-12 19:12 UTC, Betchika99 commented on source/tree.js
> +        let maxCountSpaces = treeSize - 1;
почему ты здесь используешь ключевое слово `let`?

2022-02-12 19:12 UTC, Betchika99 commented on source/tree.js
> +    }
этот блок кода вызывается один раз, зачем тогда делать ее отдельной функцией?)

2022-02-12 19:12 UTC, Betchika99 commented on source/tree.js
> +    }
хорошо, что ты научился работать с локальной и глобальной областью видимости. Но как тебе уже писала Наташа, здесь использовать замыкания не нужно. Давай попробуем переписать эти функции, чтобы они не изменяли переменные из внешнего окружения, а только возвращали новый результат, который в основной функции будет использоваться

2022-02-13 11:30 UTC, Andrey123815 commented
> привет)) добро пожаловать на курс по Фронтенду))))
> 
> ты неплохо решил задачу, молодец :) отдельно хочу отметить, что ты хорошо декомпозируешь код, что делает его более читабельным. это тебе отлично поможет в будущем проекте.
> 
> есть несколько комментов к твоему коду, обрати на них внимание. а еще поисследуй и расскажи про использование `this` в коде JS. что это за слово, за что оно отвечает, как мы можем его изменять. Коротко и по сути :)
> 
> если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)
> 
> после того, как поправишь, напиши здесь коммент "Готово" плз :)
this - это ссылка на обьект, который вызвал данный метод. Изменять его можно например вызвав у другого объекта какой-нибудь метод.

2022-02-13 11:36 UTC, Andrey123815 commented
> привет)) добро пожаловать на курс по Фронтенду))))
> 
> ты неплохо решил задачу, молодец :) отдельно хочу отметить, что ты хорошо декомпозируешь код, что делает его более читабельным. это тебе отлично поможет в будущем проекте.
> 
> есть несколько комментов к твоему коду, обрати на них внимание. а еще поисследуй и расскажи про использование `this` в коде JS. что это за слово, за что оно отвечает, как мы можем его изменять. Коротко и по сути :)
> 
> если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)
> 
> после того, как поправишь, напиши здесь коммент "Готово" плз :)

Готово

2022-02-13 13:06 UTC, Andrey123815 commented
> > привет)) добро пожаловать на курс по Фронтенду))))
> > ты неплохо решил задачу, молодец :) отдельно хочу отметить, что ты хорошо декомпозируешь код, что делает его более читабельным. это тебе отлично поможет в будущем проекте.
> > есть несколько комментов к твоему коду, обрати на них внимание. а еще поисследуй и расскажи про использование `this` в коде JS. что это за слово, за что оно отвечает, как мы можем его изменять. Коротко и по сути :)
> > если будут вопросы, [пиши в тг](https://t.me/emdobryanskaya)
> > после того, как поправишь, напиши здесь коммент "Готово" плз :)
> > this - это ссылка на обьект, который вызвал данный метод. Изменять его можно например вызвав у другого объекта какой-нибудь метод.

Готово

2022-02-13 20:10 UTC, closed without merging